### ISSUE TITLE
Settlers mine tiles instantly

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#100]
Tested it on hills & mountains

**Comment by SWY1985** [comment]
Nope, look at the year of the game.
Game automatically skips all turns until the mines are finished. This is due to the End of Turn message being turned off.
I have a fix for the issue.

**Comment by iStruggle** [comment]
I know this is closed but end of turn should still appear even when turned off if there are no active units to move, eg settlers that are mining. That is, if a unit is available to move at the start of the next turn, there shouldn't be an end of turn message beforehand.

**Comment by SWY1985** [comment]
Yes, that is how it is now.

**Comment by SWY1985** [comment]
I have fixed it correctly, just not in the preview yet. :-)
