### ISSUE TITLE
Cities with city walls should have a thick black/gray square line around the city ...

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#101]
... visible in the map.

**Comment by iStruggle** [comment]
Building effects are yet to be implemented, I guess this means graphically as well =]

**Comment by SWY1985** [comment]
It's true, building effects are not yet implemented, but I will keep this issue open to remind me...

**Comment by SWY1985** [comment]
I never noticed it until today: The big black border is the same as the Foritify border for units.
