### ISSUE TITLE
City grows beyond 10 without the aqueduct

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#105]

**Comment by iStruggle** [comment]
I think city building effects are yet to be coded.

**Comment by SWY1985** [comment]
Building effects have not been implemented.

**Comment by SWY1985** [comment]
What happens to the food storage when the city should grow beyond 10 but there's no aquaduct? Will it remain full?

**Comment by iStruggle** [comment]
I think so, with a popup each turn to say that that city requires an aqueduct for further growth. Will check it tonight if no one else has by then =)

**Comment by SWY1985** [comment]
Thank you.
Also, if you can, please make a screenshot (Ctrl+F5) of the popup in the original game and upload it.

**Comment by iStruggle** [comment]
Ok so, I was wrong.  After popup is given about aqueduct, food storage drops back.  In this case to 7 units past the granary line (tested twice), and just 2 units without a granary which is the excess food for this city.  Not sure why granary is 7 (or 5 once you take into account the 2 produced that turn).  Have only tested with this one city but have the save if someone else wants to test further before I can. Please note that the resource fields are different for the 7 screenshot and the 2 screenshot, but one of the 'with granary' tests was with the same resources as the 2 screenshot. If that makes sense?!?
![civ_002](https://cloud.githubusercontent.com/assets/17543417/18449780/73373b68-7928-11e6-8ca8-7845402ea592.png)
![civ_003](https://cloud.githubusercontent.com/assets/17543417/18449782/759f7dc0-7928-11e6-964a-ef746aaf4d07.png)
![civ_004](https://cloud.githubusercontent.com/assets/17543417/18449786/77c80d24-7928-11e6-9b83-4b1bd8e0cc2e.png)

**Comment by iStruggle** [comment]
EDIT BUT NOT REALLY: Just thought, Granary version had 1 space left on the turn before the city should have expanded, leaving 1(of the 2 food produced each turn) to spill over.  This may mean that granary mode dropped back to 4 (1 for spillover, and 2 for that turn's production).  Non Granary mode, the box was perfectly full the turn before.  Will investigate further but can't do tonight I'm afraid!

**Comment by SWY1985** [comment]
Really nice, thank you for the screenshots. This will help implement both the Aquaduct and the Granary building effects.

**Comment by SWY1985** [comment]
![capture00005](https://cloud.githubusercontent.com/assets/9248547/18451907/2d992d76-7939-11e6-988b-e14e51e03ed7.png)

This is a screenshot from CivOne.

**Comment by SWY1985** [comment]
Fixed dialog.

**Comment by iStruggle** [comment]
I think there might be a little more to the granary effect with the aqueduct thing. I would like to test different circumstances to find out exactly what goes on and will post here and on cff
