### ISSUE TITLE
Map centres to already on-screen unit.

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#106]
Sounds odd, but most noticable with a new game and just 1 settler.

Civ allows a unit to move upto 6 map sqaures away from the centre of the screen before recentering on that unit.  When the key is pressed to move the unit, the screen should centre on the square the unit is currently in as the movement animation is played.

**Comment by SWY1985** [comment]
This bug was introduced due to some experimental unfinished AI code. I will find a good solution for this.
