### ISSUE TITLE
If production in a city is negative, delete unit/units belonging to this city

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#113]
Delete such a number of units, so that the production is not negative any more.

It seems that units away from the city are deleted first. Next come units that are in the city but are less advanced (e.g. militia over phalanx). I'm not entirely sure how the mechanics behind this work.

**Comment by kazgaroth011** [comment]
btw, issue #100 should be opened again (end of turn)

**Comment by SWY1985** [comment]
Needs a special dialog as well, giving you the one option: Disband Unit.
Will try to add this function soon.
