### ISSUE TITLE
On EARTH chosing English civ usually makes the game crash

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#115]
The starting settler is (in most cases) placed somewhere near the arctic and immediately after the game crashes. Getting similar problems by choosing Greeks (same color).

Tried it with other civs and no such problems.

UPDATE: The game is very unstable on EARTH. Usual crashes after only a few turns.

**Comment by SWY1985** [comment]
I can imagine why this happens, but it's not intentional. The problem should be fixes along with #114.

**Comment by SWY1985** [comment]
Well... starting positions on EARTH are still random, and somehow the EARTH map invites the game to spawn civilizations on one of the poles which causes the game to try and center over the edges of the map.
I have taken precautions, that fixes this bug. Now I just need to get the EARTH start positions correct...
