### ISSUE TITLE
Can see enemy settler movement at the beginning of the game

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#117]
Despite it being in unexplored terrain. Before this I used shift+5+6. Will test out if this has any effect.

**Comment by SWY1985** [comment]
This is a known issue, I'll close this issue once I've got a fix for that.

**Comment by iStruggle** [comment]
Yeah, I've seen enemy movements in undiscovered terrain too - militia.

**Comment by SWY1985** [comment]
This has been fixed along with #120
