### ISSUE TITLE
Enemy city occupies production square despite my unit's presece there

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#118]
In the lower left square:

![capture00001](https://cloud.githubusercontent.com/assets/21365802/18484008/f659344c-79e6-11e6-9865-06df2b2c3976.png)
![capture00002](https://cloud.githubusercontent.com/assets/21365802/18484009/f67ebe74-79e6-11e6-9e3d-81df63f4b187.png)

**Comment by SWY1985** [comment]
Cities do not take units into account yet, will try to solve this soon
