### ISSUE TITLE
opening sequence fade is now very slow

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#120]
actually, the game appears to run slow.  Smooth (which is beautiful by the way!) but slow.

**Comment by SWY1985** [comment]
I'm going to implement an option to switch between smooth and fast graphics. Unfortunately it's necessary for the moment.
I'm fighting with Windows GDI+ to get all the frames out as fast as possible. I know how to solve it, but that would mean a rewrite of the graphics processor #40. I don't want to do that before version 0.1.0.

**Comment by iStruggle** [comment]
Ahh.  You see that's where my knowledge becomes woefully incomplete =]

I have noticed its gotten worse with later releases but if it's in hand then all is well =]
