### ISSUE TITLE
Possibly related to #57, crash when naval unit turn starts offscreen

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#127]
I've mentioned before and tagged in #57 but can't reproduce reliably.

Had it again tonight though in latest 527 build.  Definitely upon starting a turn with an offscreen naval unit (trireme this time, away from land) but does not appear to occur every time.

Not sure if this helps, Error report:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	civone.exe
  Problem Signature 02:	0.1.0.0
  Problem Signature 03:	57d80d16
  Problem Signature 04:	CivOne
  Problem Signature 05:	0.1.0.0
  Problem Signature 06:	57d80d16
  Problem Signature 07:	757
  Problem Signature 08:	0
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	2057
  Additional Information 1:	48f3
  Additional Information 2:	48f3caff84f0073211477328e1e01226
  Additional Information 3:	431e
  Additional Information 4:	431e697fab0030dcb99e8afab0c611fd

**Comment by SWY1985** [comment]
Thank you for the info and the log. It should help in finding out what's going wrong.

**Comment by SWY1985** [comment]
Can you confirm that this happens when the boat is close to one of the poles?

**Comment by SWY1985** [comment]
Confirmed, this has been fixed in a recent commit.
