### ISSUE TITLE
Sometimes game crashes on 1st turn

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#128]
In rare cases when enemy civs start making moves in the first turn (after my own first turn), the game suddenly crashes. I get the feeling this keeps happening when you choose large map size in customize world, but this theory needs more testing.

**Comment by SWY1985** [comment]
It also happens with normal maps sometimes. I can reproduce it, will fix it soon.

**Comment by SWY1985** [comment]
Fixed along with #115.
