### ISSUE TITLE
When city builds a settler, the settler should not be visible & flashing like it's active

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#129]
The screen should just freeze without the settler visible. 
Yes I am running out of bugs to report, just put this into lesser priority list.

![capture00002](https://cloud.githubusercontent.com/assets/21365802/18491231/b7379e6a-7a05-11e6-95db-c83de4999437.png)

**Comment by iStruggle** [comment]
This is for all popups. Any popup should freeze the game behind until cleared. Also sidebar is blank with popup open.

**Comment by SWY1985** [comment]
Known issue, linked to #110.
