### ISSUE TITLE
City food production in tiles often changing by itself

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#130]
I eventually changed gov. from despotism to monarchy. 
City food production in tiles now seems to change every couple of turns, as if the gov. type keeps switching from despotism to monarchy back and forth by itself.

**Comment by SWY1985** [comment]
Yeah... I've gone about terrain resources the wrong way, I need to rethink that.
Right now, the game asks for the terrain resources for the current player, which in theory should be fine, but in reality isn't.
Thinking about a fix... may take some time.
