### ISSUE TITLE
No penalties exist for units moving from road to some tiles

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#132]
E.g. if units have 2/3 or 1/3 movement left they shouldn't always successfully move to mountains/hills/forest/swamps.

**Comment by SWY1985** [comment]
Does anyone know what the odds are of failing to move, otherwise I'll have to test that...

**Comment by kazgaroth011** [comment]
I'll do a bunch of moves and test this.

**Comment by kazgaroth011** [comment]
Moved militia to a forest tile from a rod about 100 times.
Results:
- 1 turn left: 100% chance (didn't really test this)
- 2/3 turns left: 50% chance
- 1/3 turns  left: 33% chance

Quite expected. What about other tiles or units with >1 movement? Will have to test it out.

**Comment by SWY1985** [comment]
Once again, amazing testing skills, thanks a lot!
I'll be sure to get this implemented in the next preview.

**Comment by kazgaroth011** [comment]
Well I tried about 270 times to move my militia swarm with 2/3 turns left to a hill. 
And the results are strange. There is no clear convergence toward 50% (the graph below shows success rate of moving onto a hill). Rather it oscillates between 40 and 45 % and perhaps the strangest is the late swing in oscillation.

Questions:
- does the fact that you have 1 unit already present on the hill affect your chance of successful move?
- what kind of RNG was Sid using?
- why did I uninstall IDA?

![clipboard04](https://cloud.githubusercontent.com/assets/21365802/18527377/ce399fd6-7ac4-11e6-806c-64f8b7f3e9c2.png)

**Comment by SWY1985** [comment]
Your dedication is truly amazing, thanks for the effort.
Looking at this, I'd say it's a change of 3 out of 7, which is 42.85%.

**Comment by kazgaroth011** [comment]
Before this test I did about 100 iterations and it stabilized at about 55%. It can be dependent on the type of random number generator, but my best guess is that you should just put it at 50% (for 2/3 turns left) and 33,33% (for 1/3 turns left).

I'll also do a check for the mountains.

**Comment by SWY1985** [comment]
I have fixed this according to your suggestion: On terrain with movement penalty, there's a 33.33% chance for 0.1 moves and 50% chance for 0.2 moves.
If there's an update on this mechanism, please update post to this issue so I can reopen it, or create a new issue.
