### ISSUE TITLE
At the end of turn money count (below the minimap) changes twice

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#137]
It goes from 134 to 137 and 140. 137 is barely visible, but still visible.

**Comment by SWY1985** [comment]
The same thing happens in the original game, but in the background: You can see the money changing between city actions, since calculations are done per turn, per city.
I will try to move this actions more to the background.

**Comment by kazgaroth011** [comment]
That may indeed be true. I also checked in the original CIV that the date is changed first and then the money, as is in CivONE, so this works well.

**Comment by SWY1985** [comment]
Good news everyone!
I have attempted to fix the task slowness and it's once again blazingly fast.

**Comment by kazgaroth011** [comment]
Best news of the day.
