### ISSUE TITLE
End of turn actually happens before the end of the turn.

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#141]
Ever so slightly, the task indicator appears just before the turn ends, causing a split-second pause in the movement of a unit, or discovery of a map area.

If you move a unit, maybe 2 pixels before it reaches its destination, the game pauses as the task indicator appears, then the unit finishes its move.  Sometimes more noticeable than other times.

Might be related to #139?

**Comment by SWY1985** [comment]
This issue has been resolved
