### ISSUE TITLE
first settler still appears in city window after founding.

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#142]
not sure if this is the case with all settlers.

EDIT:Yes, all new cities do this.

**Comment by SWY1985** [comment]
I made it that way because that's what happens in the original game as well...

**Comment by SWY1985** [comment]
Am I correct? Can I close this issue, or did I make a mistake?

**Comment by kazgaroth011** [comment]
In the info screen? Yes the settler must be there so you can close it.

**Comment by iStruggle** [comment]
Woo my bad! Thought I saw this as an issue a while ago that had closed and assumed it was not usual behaviour. =p

**Comment by SWY1985** [comment]
No problem. :-)
