### ISSUE TITLE
City improvements upkeep costs are not implemented yet.

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#144]
But actually this is really helpful for testing at the moment.

**Comment by SWY1985** [comment]
I'll need to add some patches to the setup screen, so you can cheat for the purpose of testing the game:
- Instant discovery
- Extra gold
- Instant buy

City improvement upkeep will be implemented quickly.

**Comment by iStruggle** [comment]
yeees....testing purposes... <eyes move shiftily side to side> lol!  But thats great =]

**Comment by SWY1985** [comment]
Forgot to mention with recent commit: Building upkeep is now implemented, but I'll keep this issue open for the following:
- Cheats (for testing purposes of course)
- Selling buildings
- City losing money warning
- City can't maintain message
- F5 Trade screen

**Comment by SWY1985** [comment]
Since upkeep costs have already been implemented, this issue can close. I've created issues #200, @201 and #202 for the specific features mentioned above.
