### ISSUE TITLE
Unlimited (?) settlers spawned at the beginning of the game

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#161]
Not that I'm complaining ...

EDIT: Not unlimited, just a lot.

**Comment by SWY1985** [comment]
Oh no... That's test code that shouldn't be there. I'm going to replace it within an hour...

**Comment by SWY1985** [comment]
It was 20, along with the original 1 or 2 you were supposed to get.
I needed to test if the Report screens (F1, F4, F5) worked correctly with multiple pages so I needed a lot of cities quickly.
I accidentally committed the code.

The changes are now reverted and I've placed preview r613 on the forums.
