### ISSUE TITLE
Tiles next to cities can be irrigated only if adjacent to ocean/river

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#164]
Even though a city technically automatically has irrigation.

**Comment by SWY1985** [comment]
I thought I had added the city exception but apparently not. :-)

**Comment by iStruggle** [comment]
umm, yeah I havent had this::
![civone6](https://cloud.githubusercontent.com/assets/17543417/18725685/317efb76-8039-11e6-8b2b-79ff34456abe.png)
