### ISSUE TITLE
Instant built building builds instantly... lol

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#166]
What I mean is that you get the animation straight after clicking exit.

Or at least it just did with my granary but not other buildings.  Will research further and edit.

USELESS EDIT:  Damn!  I should have titled this 'Instantly built building built instantly' =]

**Comment by SWY1985** [comment]
When end of turn is off, and you build a city with your last Settler, enter the city and immediately buy a building, once you exit the city the next turn will start.
I'm not sure if this is correct: I believe that in the original, when you build a city with your last unit, the next turn will start upon exit as well.
Will research...

**Comment by iStruggle** [comment]
In that case, there should be an end of turn (press enter) as there are no active units prepared to move.

**Comment by SWY1985** [comment]
Try this in the original game:
- Start a new game
- Build a city
- Sell Palace
- Buy Barracks
- Exit city manager
- Wait for it...........

**Comment by iStruggle** [comment]
On it. hang on

**Comment by SWY1985** [comment]
It's not instantly in the original game because the original game takes a longer time to process enemy turns.
I might need to add a small delay to auto end of turn.

**Comment by iStruggle** [comment]
Well, I couldn't reproduce it, and unless there are other reasons to add a delay, I wouldn't - the game feels very nice with it flowing so well...

**Comment by SWY1985** [comment]
I sometimes get confused about when the next turn starts. Especially when moving around with a single unit. A minor delay may take away some of the confusion.

**Comment by iStruggle** [comment]
wait wait wait.  You're right.  In these instances, you see a glimpse of the main map screen after exiting manager and then the building animation happens.  THAT'S why it didn't quite feel right!

This should also happen when two cities finish building in the same turn I believe.  Delay would fix this but a teeny one!
