### ISSUE TITLE
Bought large building shields overspill the window

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#167]
![civone3](https://cloud.githubusercontent.com/assets/17543417/18724810/a6fea04e-8035-11e6-8104-791be1e8580a.png)
Hanging gardens in this case. will post ss in a sec

**Comment by SWY1985** [comment]
I haven't got the shield stacking in the production frame right... yet.

**Comment by iStruggle** [comment]
ah ok. ss added anyway =]
