### ISSUE TITLE
Game hangs on Quit to Dos

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#168]
I thought this was known, but couldn't find the open issue.

Interestingly, I can still right click to see terrain info, though it only appears to show ocean regardless of where I click.  Can't do anything else though.

**Comment by SWY1985** [comment]
Oh no, I thought I fixed this...
I was able to reproduce it, then I made some changes and it stopped happening. Apparently, my previous fix did not help.

**Comment by iStruggle** [comment]
Yeah, I can't remember ever having this in previous testing, but then, I can't actually remember if I just clicked the cross to close the window...

**Comment by iStruggle** [comment]
whoops.  didnt mean to do that

**Comment by SWY1985** [comment]
I actually want to (eventually) open the quit to dos dialog when clicking the Window close button... but that's not a good idea if that causes the game to hang. :-P

**Comment by kazgaroth011** [comment]
Can confirm that this happens every now and then ...

**Comment by SWY1985** [comment]
I believe this issue should be solved now. I've completely rewritten the Quit to DOS dialog. Can not really test it as none of my computers have this problem.
