### ISSUE TITLE
No text on taskbar icon when right clicked - win7

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#169]
screenshot is easier than explaining.

When hovering (no problem):
![hover](https://cloud.githubusercontent.com/assets/17543417/18724724/511b76d4-8035-11e6-81bd-8d0537a79868.png)

on right click:
![right click](https://cloud.githubusercontent.com/assets/17543417/18724725/533facf0-8035-11e6-9f14-712614275f35.png)

**Comment by SWY1985** [comment]
Can't reproduce this on Windows 10. I'll make a virtual machine with Windows 7 to reproduce this... going to take some time.

**Comment by iStruggle** [comment]
not major issue.  Is there anything I can do to help, save you sorting out a VM?

**Comment by SWY1985** [comment]
Oh no, don't worry, installing Windows is one of my hobbies... and I've got an MSDN licence from work so I can legally install Windows 7 in a virtual machine. I mean to test on different Windows versions anyway.

**Comment by SWY1985** [comment]
This issue is resolved... although the game doesn't have an icon at all at the moment, I will implement better OS integration at a later time.
