### ISSUE TITLE
Popups should pause game.

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#170]
Related to other issues as well maybe,  Game should be paused and sidebar blank when all popups and news banners show.

Original Civ:
![civ_005](https://cloud.githubusercontent.com/assets/17543417/18725410/171b59e2-8038-11e6-91cc-20ec756b86f8.png)

Civone (cavalry flashing):
![civone4](https://cloud.githubusercontent.com/assets/17543417/18725501/68afc95a-8038-11e6-8a21-72c165e1f418.png)
![civone5](https://cloud.githubusercontent.com/assets/17543417/18725503/6ae304a8-8038-11e6-9704-3a8ce26d9e95.png)

**Comment by SWY1985** [comment]
Linked to #110 and #129. I promise I'll fix it this time.
