### ISSUE TITLE
Game tends to crash after buildings are built

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#172]
Happened to me about 5 times already. As soon as some city improvement is built, the game crashes. Not always though.

**Comment by SWY1985** [comment]
Can confirm: I've played games until I discovered everything to about the year 2200 AD without any problems, but sometimes the game crashes before 1 AD.
Do you get some kind of error message? If so, can you make a screenshot?

**Comment by kazgaroth011** [comment]
This is a screenshot when I moved a settler down 1 tile and the game suddenly crashed:
![clipboard02](https://cloud.githubusercontent.com/assets/21365802/18726969/09544d28-8047-11e6-8143-a4afdd1b7fa8.png)

This second time I built barracks & city walls. All OK. But it crashed when I built pyramids:
![clipboard04](https://cloud.githubusercontent.com/assets/21365802/18726998/2708beee-8047-11e6-993a-c5db157aea28.png)

**Comment by iStruggle** [comment]
I've had this after a building completes, on the manager screen:
![image](https://cloud.githubusercontent.com/assets/17543417/18727248/b695a714-803f-11e6-8aac-57eef1426448.png)

**Comment by SWY1985** [comment]
Okay, so I specifically need to look for a NullReferenceException. This helps a lot.

I discovered that the game crashes whenever you build one of the Space Ship components, so whatever you do: Don't build Space Ship parts!

**Comment by iStruggle** [comment]
And again, haven't checked to see if this is the same error:
![image](https://cloud.githubusercontent.com/assets/17543417/18728064/7445947e-8043-11e6-81dc-2cda167c0688.png)

This might make a difference:  I was hammering through turns and screens just to progress some techs - literally spamming the enter key.

**Comment by SWY1985** [comment]
I think there's a problem with resources not yet being loaded...
Only proper debugging will tell me what actually happens. I will explicitly hammer the enter key while debugging. :-)

**Comment by SWY1985** [comment]
There was a bug with getting graphics resources. That issue has been fixed.
I have played a game until 2020 AD, where I had more than 20 cities, boats, airplanes and I had discovered all techs. The game has not crashed. It appears that this issue has been fixed.
