### ISSUE TITLE
no text in manager for Magellan and copernicus.

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#173]
![civone7](https://cloud.githubusercontent.com/assets/17543417/18726746/b7184c98-803d-11e6-9791-b76fbaee8d88.png)

Not sure if this applies to other wonders yet - limited by tech in this current game

**Comment by SWY1985** [comment]
My gut says it's got something to do with the single quote character. I'll look into this...

**Comment by iStruggle** [comment]
Also shakespeare so could be right about that.

**Comment by SWY1985** [comment]
![civ_074](https://cloud.githubusercontent.com/assets/9248547/18726862/a0813d2e-8046-11e6-9cf6-8850c775b6c3.png)

Nope... it's because the text is too long. The original game checks the length and breaks it off with a period if it's too long.

**Comment by iStruggle** [comment]
Ahh - well spotted =]

**Comment by iStruggle** [comment]
Also in the buildings list: 
![civone8](https://cloud.githubusercontent.com/assets/17543417/18726974/ada982de-803e-11e6-81c3-08a861797c64.png)

**Comment by SWY1985** [comment]
Nice, will include that in the fix. Working on it right now. :-)

**Comment by SWY1985** [comment]
BTW, you can make screenshots with Ctrl+F5. They will end up in the /capture folder.

**Comment by iStruggle** [comment]
That's just in dosbox isnt it?

**Comment by SWY1985** [comment]
CivOne as well... also Ctrl+F6 will make a picture of the (current) world map.

**Comment by SWY1985** [comment]
![capture00008](https://cloud.githubusercontent.com/assets/9248547/18727358/8194c37a-8048-11e6-8911-a1e3362281df.png)

Fixed. :-)

**Comment by iStruggle** [comment]
Nice!  Now do I have to play an original game all the way through to make sure you've abbreviated them all in the right places? =p

**Comment by SWY1985** [comment]
I've tested a few of them... it's easier when you have a build environment set up. I can easily allow building all wonders at the start of the game... or, you know, give myself 20 settlers at the start of the game.
