### ISSUE TITLE
Allow renaming city

### ISSUE THREAD

**Issue by SWY1985** [SWY1985/CivOne#174]

**Comment by kazgaroth011** [comment]
Can that actually be done in the original civ1?

**Comment by SWY1985** [comment]
I believe it can be done in version 47x.05. There's a rename button to the left of the exit button:

![image](https://cloud.githubusercontent.com/assets/9248547/18728082/e3cc63ba-804b-11e6-9473-3e12407d1295.png)

I'll try to find an actual screenshot...

**Comment by SWY1985** [comment]
![civ_006](https://cloud.githubusercontent.com/assets/9248547/18728143/32f32fb4-804c-11e6-9201-afd1a3ae1834.png)

Here it is...

**Comment by kazgaroth011** [comment]
Interesting, never knew that actually existed. My childhood was based on 475.01 it seems.

Did some reading on http://www.civfanatics.com/civ1/faq/civfaq2.php and forums regarding the rename feature and it seems it was introduced in 475.03.

However SHIFT+56 doesn't seem to be working on my Dosbox v475.01. No idea why.
