### ISSUE TITLE
Varying movement speed of units

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#176]
Not really a bug, just a performance issue and something I noticed. 
Movement speed of units seems to vary from fast to slow to fast etc. Resetting the game doesn't help. I haven't noticed anything unusual with CPU usage. This was something I noticed in earlier builds but didn't bother asking about it.

**Comment by SWY1985** [comment]
The frameskipping might fix it... the rewriting of the canvas/picture system most definitely will fix it.

**Comment by SWY1985** [comment]
This appears to have been fixed.
