### ISSUE TITLE
Naval units carrying other units should always have a shadow

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#178]
Without the shadow, even though it's carrying a settler:
![capture00002](https://cloud.githubusercontent.com/assets/21365802/18765510/4d1a736e-8116-11e6-8200-abf088a8e6b4.png)

In the next turn it's OK again:
![capture00001](https://cloud.githubusercontent.com/assets/21365802/18765518/5451b386-8116-11e6-9d59-5bd7de366744.png)

**Comment by SWY1985** [comment]
It is a known issue but I haven't made a report of it yet. Will fix this one.
