### ISSUE TITLE
Unit moving towards the last polar tiles (end of map) crashes the game

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#179]

**Comment by SWY1985** [comment]
I don't think I understand what you mean here. Are they moving from the right to the left side of the world?

**Comment by kazgaroth011** [comment]
I unloaded my settler 2 tiles below the northern edge of map. Then it made a move 1 tile north (basically to the edge of map), and the game suddenly crashed.

**Comment by SWY1985** [comment]
Thank you, I will work on a fix.
