### ISSUE TITLE
Text in the left tab is under the pictures of units

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#182]
Observe (from CivONE=right, dosbox original CIV1 = left):
![clipboard02](https://cloud.githubusercontent.com/assets/21365802/18766334/053093c2-811a-11e6-8866-c3a13a1b700c.png)

Perhaps moving the pictures of units further down?

**Comment by SWY1985** [comment]
Ah, that's because of the added Veteran label. Hadn't taken that into account.
