### ISSUE TITLE
Deleting a unit with CTRL+D does not work

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#186]
At least in my case.

**Comment by SWY1985** [comment]
Should be Shift+D... does Ctrl+D work as well? Need to test it...

**Comment by kazgaroth011** [comment]
Shift+D works ok.
I remember using CTRL+D extensively, but I can't remember if it was in Civ1 or 2. Once CTRL was activated you just kept pressing D.

**Comment by SWY1985** [comment]
Might have ben Civ1 for Windows and Civ2.

**Comment by iStruggle** [comment]
SHIFT +D for disband as it is a Capital D in the order menu.  CTRL+D has never worked for me.

**Comment by SWY1985** [comment]
I believe I can close this issue.
