### ISSUE TITLE
Game crashes after pressing CHANGE in the city view

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#187]
More specifically, it happens when you build a city improvement and then don't change the production. After some time the shield count fills up. At some point, the game crashes when you want to change production.

EDIT: Crashes randomly when pressing change just as well, no matter the shield count. So you can flush this issue down the toilet, it was reported before.

**Comment by SWY1985** [comment]
It's possibly an overflow issue, although I did make some changes to the code. Does this still happen in the latest version? If so, do you see any error message?

**Comment by SWY1985** [comment]
Could no longer reproduce this.
