### ISSUE TITLE
Minimap does not update main screen correctly.

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#188]
Reported by Laterego on CFF:

I noticed a possible bug with the minimap.

If you have a current unit (blinking) you can change the map position by clicking in on the minimap. The map will update correctly if you select a spot in which the unit is still visible. Othewise, using the minimap does not update the map right.
---
They're right:
![capture00002](https://cloud.githubusercontent.com/assets/17543417/18797757/5cc9de7e-81c7-11e6-948b-b0b7ef6ac786.png)
The unit in question stops flashing also.

**Comment by SWY1985** [comment]
I need to test this, I have already created a fix for the minimap where it would not work at the end of the turn and I'm not sure if that also fixed this issue.

**Comment by SWY1985** [comment]
The bug still exists, will create a fix for it.

**Comment by SWY1985** [comment]
I can no longer reproduce this, so I think it's fixed now.
