### ISSUE TITLE
City improvements fall off the bottom of the window in manager when there are too many.

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#189]
There should be a more button for a second page.  Will try to upload a second screenshot from original civ.

The issue::
![capture00003](https://cloud.githubusercontent.com/assets/17543417/18798141/f4c97b5c-81c8-11e6-8982-31e9bc49ec2b.png)

**Comment by SWY1985** [comment]
This has already been implemented in these commits:
https://github.com/SWY1985/CivOne/commit/04284ebb6a550830034a063b13ecc4f661755b3f
https://github.com/SWY1985/CivOne/commit/74c6dd820b34c54345a904abcad4b21109098ebf
