### ISSUE TITLE
Long pause after telling settler to build a railroad.

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#190]
maybe a second or so.  Checking to see if there's road already in the map square maybe?

**Comment by SWY1985** [comment]
Does this happen every time?
I did not have this problem on my development PC, will have to test it on my tablet.

**Comment by kazgaroth011** [comment]
There is always a slight delay even when you want to build a road. It depends, for me sometimes these delays are hardly noticeable, at other times they last a fraction longer, but I never had to wait for as long as 1 second.

**Comment by iStruggle** [comment]
road doesnt seem to be as bad for me as railroad.  In fact I don't really see any delay for roads, irrigation and mines.

**Comment by SWY1985** [comment]
Is this still an issue?

**Comment by SWY1985** [comment]
I have not been able to reproduce this issue, I'm going to close it.
