### ISSUE TITLE
Overlapping menus when changing gov. & building improvement

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#194]
When both are achieved at the same time, you may get this:
![capture00010](https://cloud.githubusercontent.com/assets/21365802/18807385/7afe960e-8245-11e6-9208-f6d49d0ec1da.png)

**Comment by SWY1985** [comment]
Oh, yeah... I had this once when I made a discovery. It gave me two menus at once.
I will need to make changing governments a task as well.
