### ISSUE TITLE
With lighthouse effect, units do not get additional turn when built

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#195]
Tested this on trireme. Basically when it gets built it has 3 turns, but in the next turn 4 turns.

**Comment by SWY1985** [comment]
Alright... I believe this means that the game handles unit actions first, then city actions. I did this the other way around. Hopefully, by reversing this, I won't introduce any new bugs. :-)

**Comment by kazgaroth011** [comment]
This should be opened again. When I build my sail, it has 3 turns (when leaving the city). In the next turn it has 4 turns.

**Comment by SWY1985** [comment]
Doesn't it now work like it's supposed to? I remember testing it against the game. The turn that the Lighthouse gets built, your unit still has 3 turns. Only the next turn will it get 4. I will need to test this.
