### ISSUE TITLE
Settlers don't show up on EARTH at start

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#198]
Happened to me once with Mongols and several times with Indians. Haven't tested it on all the civs though.

![capture00001](https://cloud.githubusercontent.com/assets/21365802/18811525/f93593c0-82b2-11e6-901c-788ead454125.png)

**Comment by SWY1985** [comment]
I placed the fixed starting positions in the code, but after that the game was still performing the random map placement checks. The Indian starting position failed the check, and the game decided not to spawn the Settlers at all.
I've fixed it.
