### ISSUE TITLE
Implement city management screen

### ISSUE THREAD

**Issue by SWY1985** [SWY1985/CivOne#20]

**Comment by SWY1985** [comment]
= City Management Screen:
- There should be spaces between Happy, Content, Unhappy, Entertainers/Tax collectors/scientists (not between these 3) and citizens. Also entertainers in city size 1 (like you ever would!) also have a space first, then the entertainer.
- Unable to change entertainers into taxmen or scientists. Clicking leaves management screen (WIP?)
- Creating entertainers does not (yet) create luxuries or happy citizens.
- Nearby cities are currently able to share map squares for resources.
- City management screen does not show food deficits (black icons). Also shields. Not yet sure about trade. (deliberate for now?)
- Food consumption maths is off. Should be 2n+1 where N is city size (at least on chieftain - yet to test other difficulties).
- After 'buying' a unit, clicking change before leaving (or building the unit, ie while production window for the unit is full of shields) shows cheaper units as taking 0 or negative amounts of turns - this should read 1.
- Clicking on the city square on resource minimap resets all entertainers and seems to prioritise shields over food. Thought you could do this in original game too (wanted to see if original prioritised food) but screen just blinked with no change? EDIT: Original game DOES reset resource fields when clicking an empty square when all citizens are workers. Original seemed to prioritise food for growth, leaving a shortage of shields for unit support under monarchy govt. when it was possible to have a balance and no shortages of food OR shields.

**Comment by iStruggle** [comment]
Please ignore my note on food consumption.  My mistake. All my other notes have now been implemented, except luxuries and happy citizens/taxmen and scientists.
