### ISSUE TITLE
Unit disbanded message for other civ appears

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#213]
Playing as an American. Got the message for the Aztecs.

![capture00003](https://cloud.githubusercontent.com/assets/21365802/19163446/4a425ad0-8bfc-11e6-9b00-66da4bfe919c.png)

**Comment by SWY1985** [comment]
Oh, yeah... that's a minor mistake. Will fix it.

May I ask, how was the game speed later into the game? I see you played until 2222 AD here. Was the game taking longer and longer every turn? Any significance with building RailRoads?

**Comment by kazgaroth011** [comment]
Yes the game slows down later on quite significantly. No idea why. One thing that is immediately noticeable is that issuing orders to a settler takes a long time (e.g. building roads/railroads), unit movement is slow...
