### ISSUE TITLE
With negative income, the currency doesn't drop to 0 completely

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#214]
In my case it dropped to 2 gold pieces, but not less.

![capture00004](https://cloud.githubusercontent.com/assets/21365802/19163652/2248b9ec-8bfd-11e6-994a-fc8ce27f5e66.png)

**Comment by SWY1985** [comment]
It should start selling buildings too.

**Comment by kazgaroth011** [comment]
It didn't.

**Comment by SWY1985** [comment]
I know, but it should... I will solve this issue along with #171. :-)

**Comment by SWY1985** [comment]
This issue appears to have been fixed: The gold value actually drops to 0 now.
