### ISSUE TITLE
Screen width/height wrong

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#228]
Observe:
![clipboard02](https://cloud.githubusercontent.com/assets/21365802/22904632/68a46444-f23d-11e6-96fb-a66dc1766045.png)

This also means that mouse pointer (torch) is offset from windows pointer.

**Comment by SWY1985** [comment]
This is a problem when you're using DPI higher than 100% in Windows. I will get this fixed.

**Comment by kazgaroth011** [comment]
BTW this is the case when the settler spawned on the hut :)

**Comment by SWY1985** [comment]
This issue has been fixed.
