### ISSUE TITLE
Started game with settler on same tile as a village

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#229]
Happened on EARTH map (playing as Americans).

**Comment by SWY1985** [comment]
I can reproduce this, need to observe the original behaviour of Civilization: I believe the original game either removes the hut before spawning a settler, or the hut positions are fixed.

**Comment by SWY1985** [comment]
On random maps, the game prevents spawning on top of a tribal hut. On the EARTH map the player positions are fixed so this mechanism is skipped. I believe the hut positions are fixed on the EARTH map. This is currently not true for CivOne.
I will remove the hut below the spawing point to prevent starting on top of a hut, that will at least fix this issue.
