### ISSUE TITLE
White lines appear on rivers, sea & irrigation in cityview

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#238]
![clipboard02](https://cloud.githubusercontent.com/assets/21365802/22951563/f94818de-f309-11e6-8512-c317bd9e494f.png)

**Comment by SWY1985** [comment]
I have also noticed artifacts, but I couldn't figure out what caused them (yet).

**Comment by SWY1985** [comment]
I've been playing for a while and I can no longer reproduce this issue. I believe I've fixed it with my latest graphics improvements.
