### ISSUE TITLE
Implement cyan highlight while moving cursor in the build menu

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#241]
Pressing the left mouse button and moving up/down through the build menu should highlight current option with cyan.

**Comment by SWY1985** [comment]
The mouse drag code must be implemented, it got lost when I switched to OpenTK.

**Comment by kazgaroth011** [comment]
Just to note that this is not working in the newest version.

**Comment by SWY1985** [comment]
I noticed, I'll reopen this issue.
