### ISSUE TITLE
Pressing sleep on trireme in the middle of the ocean shoud disband unit

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#242]

**Comment by SWY1985** [comment]
In the original game, Sentry ends the turn for any unit. When you sentry a trireme unit at sea, there's a 50% chance it will get destroyed. If it does not get lost at sea, it will remain there indefinitely.
I will make the appropriate changes to CivOne.

**Comment by kazgaroth011** [comment]
True!
