### ISSUE TITLE
Unit speed is increased for a few turns after city improvement is built.

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#244]
could just be my system? win 7 U 64.

Doesnt happen every time but units flash and move quicker for about 3 or 4 turns after a city builds an improvement.

**Comment by SWY1985** [comment]
I need to figure out what causes this. Might be a problem with the Gameplay screen.

**Comment by SWY1985** [comment]
How is this now? I believe some recent performance fixes may have resolved this issue.

**Comment by AlexFolland** [comment]
It still happens very often throughout the game, especially late in the game, after any of the many various causes of lag spikes.  One common example is after idling in the production choice window inside a city, then leaving.  It seems the blinking and animations are not based on accurate timing like using QueryPerformanceFrequency in Windows, but based on something inconsistent.

**Comment by SWY1985** [comment]
Timing issues have been solved. There should no longer be any speed changes in the game.
