### ISSUE TITLE
Correct activation unit order in cities

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#247]
Let's say two units (unit1=active and unit2=fortified) are in a city and the unit1 is waiting for its order. If the fortified unit2 is activated, it gets immediately active, and unit1 is disregarded. This should be corrected, as in the original Civ1 in this case unit1 is still first active, and only then is unit2 activated.

**Comment by SWY1985** [comment]
This issue has been fixed: 47b36621453744ede2fae1a219ec00f16e00dc46
