### ISSUE TITLE
City view buildings order

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#250]
Played the original civ till ~1 AD. Some notes:

- when building new cities, you start off with either mud huts or tents. This logic seems not to change at least until 1 AD. My capital had mud huts, 2nd city had tents, 3rd+4th had mud huts, 5th had tents, ... Seems to be random.

- brown tents seem to be the 1st stage, followed by gray tents. At around 1200 BC all my brown tents changed color to gray. No idea what triggered this.

- between 1400 BC and 1200 BC all my cities started getting a smaller number of wood+clay houses, replacing the original tents & mud huts. As the city grows the number of these houses increases in the middle of the city.

- the positioning of buildings in the city seems to randomly change as your city gets bigger.
E.g. City pop. 9:
![c1_view9](https://cloud.githubusercontent.com/assets/21365802/23180113/8fe53efa-f870-11e6-9f18-dcd4851dca96.png)
City pop. 10:
![c1_view10](https://cloud.githubusercontent.com/assets/21365802/23180120/953aef76-f870-11e6-9e13-ab5ea93b70cf.png)
No clear logic how this happens.

- An example of stacking of shields etc. in the city main view as the city grows (perhaps it will be of some help):
![c1_main1](https://cloud.githubusercontent.com/assets/21365802/23180398/99dc18d8-f871-11e6-81fc-4f54107d335a.png)
![c1_main2](https://cloud.githubusercontent.com/assets/21365802/23180401/9ca51c2c-f871-11e6-8f0c-31ded10eec7b.png)
![c1_main3](https://cloud.githubusercontent.com/assets/21365802/23180409/a31bd3b6-f871-11e6-861a-c930a675bd97.png)
![c1_main4](https://cloud.githubusercontent.com/assets/21365802/23180412/a650aa52-f871-11e6-9c36-0b6968ff83f0.png)
![c1_main5](https://cloud.githubusercontent.com/assets/21365802/23180419/abf82cb4-f871-11e6-8d0e-64c244782a4f.png)
![c1_main6](https://cloud.githubusercontent.com/assets/21365802/23180426/af69819a-f871-11e6-8d07-0290dbec2f1a.png)
![c1_main7](https://cloud.githubusercontent.com/assets/21365802/23180437/b704804e-f871-11e6-9f0e-9724e4eb608e.png)
![c1_main8](https://cloud.githubusercontent.com/assets/21365802/23180440/b99356be-f871-11e6-8bc2-900c76161d42.png)
![c1_main9](https://cloud.githubusercontent.com/assets/21365802/23180444/bc283796-f871-11e6-9eaf-4ab3ca215137.png)
![c1_main10](https://cloud.githubusercontent.com/assets/21365802/23180448/bee49eb6-f871-11e6-99b9-b3934fd3b2b6.png)
![c1_main12](https://cloud.githubusercontent.com/assets/21365802/23180458/ca56bfb8-f871-11e6-8055-7f083268574e.png)

I keep making screenshots of 5 cities (main view+city view) as they grow and as the game progresses. I'll try to resolve more game mechanics this way. Will post updates on this.

**Comment by SWY1985** [comment]
Wow, great job! This is really useful.

**Comment by kazgaroth011** [comment]
So, getting _The republic_ transforms all your mud hits and tents into wood + clay houses.

**Comment by SWY1985** [comment]
Nice find, thank you!

**Comment by kazgaroth011** [comment]
I found out that the appearance of houses is changed **every 2 advances you make**. Here's the progress (left=before, right=after advance is researched):

7th advance:
Sadly no screenshots for comparison:

11th advance:
![05_both](https://cloud.githubusercontent.com/assets/21365802/23333374/c534757c-fb8a-11e6-84a8-6604370c676c.png)

13th advance:
![06_both](https://cloud.githubusercontent.com/assets/21365802/23333376/cc13ad9a-fb8a-11e6-9e81-4af95f6648e9.png)

15th advance:
![06_both2](https://cloud.githubusercontent.com/assets/21365802/23333379/d1011090-fb8a-11e6-86ca-5b132b831fdd.png)

17th advance:
![07_both](https://cloud.githubusercontent.com/assets/21365802/23333380/d60bffb4-fb8a-11e6-9e8e-a40e6e80c0bb.png)

19th advance:
![08_both](https://cloud.githubusercontent.com/assets/21365802/23333382/de519300-fb8a-11e6-9c26-9ee05479b6ff.png)

21st advance:
![09_both](https://cloud.githubusercontent.com/assets/21365802/23333384/e76a4d1a-fb8a-11e6-869c-b7b2c1a9ac0d.png)

23rd advance:
![10_both](https://cloud.githubusercontent.com/assets/21365802/23333387/f023131a-fb8a-11e6-975f-89bae06a221e.png)

25th advance:
![10_both2](https://cloud.githubusercontent.com/assets/21365802/23333390/f6529b84-fb8a-11e6-8c56-aa580f382782.png)

27th advance:
![11_both](https://cloud.githubusercontent.com/assets/21365802/23333391/00447540-fb8b-11e6-9796-a4d0c1589801.png)

29th advance:
![13_both](https://cloud.githubusercontent.com/assets/21365802/23333392/063f7c24-fb8b-11e6-86f3-897323f07cd7.png)

31st advance:
![15_both](https://cloud.githubusercontent.com/assets/21365802/23333393/0c3733e2-fb8b-11e6-84c1-df3d56ffb836.png)

33rd advance:
![17_both](https://cloud.githubusercontent.com/assets/21365802/23333395/171819de-fb8b-11e6-9f58-438e827a6020.png)

35th advance:
![18_both](https://cloud.githubusercontent.com/assets/21365802/23333398/1caf0c5e-fb8b-11e6-9c28-3efdf0444284.png)

37th advance:
![19_both](https://cloud.githubusercontent.com/assets/21365802/23333401/293ca148-fb8b-11e6-9ed4-ca3b4b8b6dde.png)

39th advance (industrialization. It also changes citizens' appearance):
![20_both](https://cloud.githubusercontent.com/assets/21365802/23333402/2fa5549e-fb8b-11e6-9efc-c426f89c33b2.png)

41st advance:
![21_both](https://cloud.githubusercontent.com/assets/21365802/23333409/3f2f609e-fb8b-11e6-9245-17954b7a7e43.png)

43rd advance:
![22_both](https://cloud.githubusercontent.com/assets/21365802/23333412/47644ff4-fb8b-11e6-9331-73cb950d2086.png)

45th advance:
![23_both](https://cloud.githubusercontent.com/assets/21365802/23333415/4e268b36-fb8b-11e6-8fc8-d62c6c41a77e.png)

47th advance:
![24_both](https://cloud.githubusercontent.com/assets/21365802/23333418/56d442c8-fb8b-11e6-9399-39388beca97c.png)

49th advance:
![25_both](https://cloud.githubusercontent.com/assets/21365802/23333420/5ca9a350-fb8b-11e6-8767-3a0e9d7bde68.png)

51th advance:
![26_both](https://cloud.githubusercontent.com/assets/21365802/23333422/6341916e-fb8b-11e6-8afa-60531dfd7b15.png)

53rd advance:
![27_both](https://cloud.githubusercontent.com/assets/21365802/23333429/69260d62-fb8b-11e6-943c-da88ac56533b.png)

55th advance:
![28_ 55 advflight](https://cloud.githubusercontent.com/assets/21365802/23333431/700df932-fb8b-11e6-9edf-98a208e0eb21.png)

56th advance was Automobile. It changed dirt roads to asphalt & people to cars:
![28_both2](https://cloud.githubusercontent.com/assets/21365802/23333438/8b5b8bdc-fb8b-11e6-85ed-1f785da73f3e.png)

57th advance:
![29_both](https://cloud.githubusercontent.com/assets/21365802/23333441/92e2c104-fb8b-11e6-9211-1b5ae52b999e.png)

59th advance:
![30_both](https://cloud.githubusercontent.com/assets/21365802/23333444/9a1210c4-fb8b-11e6-9806-b0840b3b5a7a.png)

61st advance:
![31_both](https://cloud.githubusercontent.com/assets/21365802/23333446/a1124e5c-fb8b-11e6-9ace-aaf32c857b6d.png)

63rd advance:
![32_both](https://cloud.githubusercontent.com/assets/21365802/23333447/a59c36cc-fb8b-11e6-99c0-2c967d891de0.png)

Sadly with 3 or so advances left the game crashed and I ragequit.

Also during 47th advance the picture of scientist (Sid) changed to laboratory setting. I'll have to check if something else triggers this.

As you can see even late into the game you can still have old houses, especially with large cities. This is why smaller cities have a more modern appearance.

**Comment by SWY1985** [comment]
Funny thing, I tried the same and the changes happened with the even number of advances instead of the uneven number of advances. The changes started at the 10th advance in my game. The first wooden home appeared with the 16th advance.
I wonder what the deciding factor is for that.

As for the laboratory scientist changing: That happens with the advance after you have discovered Electricity.

**Comment by kazgaroth011** [comment]
Also - you can start with either tents or (mud) huts. Perhaps this is random.

**Comment by SWY1985** [comment]
For now, until we figure out how it actually works in the original game, I will implement it like this:

- Changes happen every 2 advances, starting at the eleventh advance
- Stone/Wood huts start at 11, full at 25
- Old houses start at 27
- Industrial houses start at at 41
- Skyscrapers start at 49, in cities with a minimum size of 9

**Comment by SWY1985** [comment]
Support for all kinds of houses is implemented, though experimental, and seems to be functioning pretty much as described above.

**Comment by SWY1985** [comment]
With all building types implemented, I will close this issue. The rest of the City View implementation will be done on issue #32.
