### ISSUE TITLE
Finish research of same advance that is set from the debug menu

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#255]
If an advance you are currently researching is called from the debug menu, it should be immediately finished and you should be given the option to choose new advance (similarly if you get an advance from the tribal hut).

![clipboard02](https://cloud.githubusercontent.com/assets/21365802/23341022/a7af11c2-fc40-11e6-9d20-3d7f9f7afbb1.png)

**Comment by SWY1985** [comment]
That is a bug, the advance is never researched and choose advance popup is never shown. Will fix it soon.

**Comment by SWY1985** [comment]
This issue has been resolved.
