### ISSUE TITLE
Disable spawning land units on sea (& vice versa) in debug menu

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#256]

**Comment by SWY1985** [comment]
I'm not sure I need to disable this, as land units can exist at sea (under a boat), and sea units can exist on land (in a city).

**Comment by kazgaroth011** [comment]
I agree. But one thing you should probably disable is spawning of units on other civ's cities and units.

**Comment by SWY1985** [comment]
Good point, and while I'm working on that I will also make it illegal for land units to spawn on a non-boat sea tile and sea units to spawn on non-city land tiles.
