### ISSUE TITLE
Make better stacking of food storage (cityscreen)

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#258]
As the city grows from 10 to 11, the food shields (bottom left) should become more compact as shown below (basically one pixel that separates them should disappear):
![clipboard02](https://cloud.githubusercontent.com/assets/21365802/23342551/1e7aa2be-fc5d-11e6-8b6e-6ca5a4df626b.png)

Currently in Civone:
![clipboard04](https://cloud.githubusercontent.com/assets/21365802/23342567/4766ef20-fc5d-11e6-9664-2d9669193386.png)

If you need help I can check what happens with this as the city grows even further.

**Comment by SWY1985** [comment]
Related to this issue: https://github.com/SWY1985/CivOne/issues/167
Need to implement better stacking. Screenshots of the original game will help greatly.

**Comment by kazgaroth011** [comment]
I'll do it just give me some time.

**Comment by SWY1985** [comment]
Thanks, great job. I will try to get this correctly implemented in the next build.
