### ISSUE TITLE
Changes in "scientist screens"

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#259]
From several playthroughs I have discovered this:

1) discovering _Invention_ changes advisors' screens from old to modern (e.g. from ancient egyptian to victorian setting in monarchy)

2) next advance (after invention) you make changes "wise men" to "scientists"

3) I am not entirely sure what triggers the change in the screen with Sid in roman dress to Sid in scientist robe with a blackboard when you make an advance. In my three playthroughs it happened with 47th advance (genetic engineering), 43rd advance (industrialization) and 45th advance (electronics). So it's probably a combination of advances you make that triggers this change (or something similar).

**Comment by SWY1985** [comment]
> 1. discovering Invention changes advisors' screens from old to modern (e.g. from ancient egyptian to victorian setting in monarchy)

This was already implemented.

> 2. next advance (after invention) you make changes "wise men" to "scientists"

Confirmed, I will change it from Medicine to the invention after Invention.

> 3. I am not entirely sure what triggers the change in the screen with Sid in roman dress to Sid in scientist robe with a blackboard when you make an advance. In my three playthroughs it happened with 47th advance (genetic engineering), 43rd advance (industrialization) and 45th advance (electronics). So it's probably a combination of advances you make that triggers this change (or something similar).

It's already known and implemented accordingly: The invention after Electricity changes Sid into the good looking guy with the ancient computer.
