### ISSUE TITLE
Cruiser only has 1 sea square visibility

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#262]
Civilopedia says Cruiser has 2 sea squares visibility, but it has only 1 here.

![image](https://cloud.githubusercontent.com/assets/601517/23487162/1ef12932-fe99-11e6-8b50-dc5d4db882be.png)

**Comment by SWY1985** [comment]
Nice find, I will fix this.

**Comment by AlexFolland** [comment]
Wow, fast!  Nice job.  :)

**Comment by AlexFolland** [comment]
By the way, your fix might be wrong.  It's only "sea square visibility".  In Civilization, Cruisers can see only 1 square of land tiles worth of distance around them, but can see 2 squares of sea (Ocean) tiles.

So, for example, if the Cruiser is beside a land mass and there is a single in-land Ocean tile, it can see the ocean tile, but not the land beside it.  Here is an example.

```
XXOXX
XLLLX
OOCOO
OOOOO
OOOOO

Legend:
X = fog of war
L = land tile
O = Ocean tile
C = Cruiser
```

**Comment by SWY1985** [comment]
Like this? Because this is how it currently works:
![image](https://cloud.githubusercontent.com/assets/9248547/23501886/0cbfe3a0-ff36-11e6-9cf3-d9479091ed7d.png)

**Comment by AlexFolland** [comment]
Yes!  Excellent.  :)  You are great!
