### ISSUE TITLE
Clicking a point on the minimap does not move the viewport to that point unless it is within the current view

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#263]
Clicking a point on the minimap does not move the viewport to that point unless the clicked point is within the current view.  Also, after clicking such a point on the minimap, clicking a tile within the viewport moves the viewport to a tile relative to the minimap-clicked point rather than the tile clicked in the viewport.

**Comment by SWY1985** [comment]
The minimap is currently not working correctly and I will attempt to get it fixed in the next preview version.

**Comment by AlexFolland** [comment]
It seems to me that it is moving the viewport to that location without updating the screen to reflect the move.  The clue is that clicking somewhere inside the viewport after clicking the minimap location acts as if the viewport had been updated.

**Comment by AlexFolland** [comment]
Some more information about this one: it seems that the only thing that matters is whether the minimap click point is within viewport range of the currently in-control unit.

**Comment by SWY1985** [comment]
The map is probably moving, but there's no update signal given to the screen. I will start working on this now.
