### ISSUE TITLE
Right-clicking to view Civilopedia entries for city improvements on the second page of the city's "Change" dialog shows previous page's entry

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#264]
If a city's "Change" dialog has multiple pages using "MORE..." and you wish to read the Civilopedia entry for an entry that's on the second page of the "Change" dialog, right-clicking that entry shows the Civilopedia entry for an entry on the previous page.

**Comment by SWY1985** [comment]
Thanks for finding this bug, I will fix it.
