### ISSUE TITLE
Nuclear unit deletes hut (may be accurate)

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#265]
When a Nuclear unit moves onto a tile where a hut exists, the hut is consumed and does nothing, and the Nuclear unit continues its turn.  I am not sure if this happens in Civilization.  I expect the hut to remain unless its effect is triggered, but Civilization may not do that.

**Comment by SWY1985** [comment]
Air units moving over huts make the huts disappear without any effect. The current implementation is correct.
