### ISSUE TITLE
Cities connected by railroad consume movement points when entering the city instead of exiting

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#267]
In the original game, moving into a city connected by a railroad does not consume movement points.  Moving from a city to a railroad tile does.  CivOne has the movement points consumed correct, but when they are consumed is not.

Personally, I would like an option to enhance the original game to not consume movement points when entering or exiting railroad-connected cities, like in Civ 2.  That would be an enhancement over the original Civilization.  That's something to think about later with enhancement options, I guess.  Accurately reproducing the original game is more important.

**Comment by SWY1985** [comment]
Confirmed, will fix this.

**Comment by SWY1985** [comment]
I will consider the patch, seems reasonable.
