### ISSUE TITLE
Windows build shows only black ({R,G,B} of {0,0,0})

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#268]
I have just attempted to follow https://github.com/SWY1985/CivOne/wiki/How-to-build-and-run-on-Windows%3F step by step very carefully.  I have the latest git commit of CivOne, I have VS Code, and it even built the project with no errors.  I have the built civone.dll file in E:\games\civone\bin\Debug\netcoreapp1.1.

![image](https://cloud.githubusercontent.com/assets/601517/23542443/f5376674-ffa1-11e6-97dd-6a5c2e0da25c.png)

As my screenshot shows, I have all the dependencies VS Code complains about when trying to use "Launch Game", but it doesn't seem to work with them anyway.  I suspect this is due to debugging not working in Windows, or the build being 32-bit, or something else like that.  I try to use 64-bit tools and builds wherever possible, though I couldn't find a 64-bit version of Visual Studio Code, but everything else I'm aware of is 64-bit.  I am not sure where the problem lies.

**Comment by AlexFolland** [comment]
Oh!  Clicking "Debug" -> "Start Without Debugging" (Ctrl+F5) does run the game!  However, the game displays nothing but black (0,0,0) currently.  I am using the latest commit, ec76d0f62dfdeab979da3d13967613abd3edd7bc.

![image](https://cloud.githubusercontent.com/assets/601517/23543512/6203900c-ffa7-11e6-9bf1-29545ae8975f.png)

**Comment by AlexFolland** [comment]
I've added a line to the Windows build guide about "Start Without Debugging".

**Comment by SWY1985** [comment]
Debugging should work, but I have only tested on Windows 10.
Does the precompiled version from the website work for you?
http://www.civone.com/files/civone-0.1.0pre-alpha1-r888-winx64.zip

**Comment by AlexFolland** [comment]
That one also runs, but also exhibits this black screen bug.

I am using an Nvidia GTX 690, for the record.

**Comment by SWY1985** [comment]
Very odd... I experience the same issue with Linux and macOS but I thought it wasn't an issue on Windows. I will need to look into this, but it's very hard to reproduce.

**Comment by AlexFolland** [comment]
Now that I can build it, I can bisect to see when it started.  I'll do that.

**Comment by SWY1985** [comment]
It probably started the moment I switched to .NET Core and OpenTK. The OpenTK.Core package might be broken...
I may need to reconsider that move, even though it brought a lot of performance improvements.

**Comment by SWY1985** [comment]
Thanks for making me look into this, I've fixed it... and now it all runs on macOS without problems (will test Linux tonight).
I've switched the OpenTK window from OpenGL 4.0 to OpenGL 1.0, which probably also disabled shaders (I believe that caused the problem). Can you update the sources and see if this fixed it, please?

**Comment by AlexFolland** [comment]
That has indeed fixed this issue!  However, there is a couple of new issues related to the software cursor.
