### ISSUE TITLE
Input latency with software cursor

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#269]
This is an extremely minor and simultaneously difficult issue which I assume you have noticed, but I'm reporting it anyway as you mentioned that every issue should be reported.  The upscaled raster cursor image can move to positions which are not pixel-aligned, though it snaps back when it can.  It is especially clear when the game is lagging, during which time, it does not snap into a pixel-aligned position.

This may be particularly difficult to solve while maintaining a hardware cursor.  Perhaps using a software cursor and rendering on a separate thread would help.  This could introduce some other issues though.

**Comment by SWY1985** [comment]
The new version uses a software cursor, so this issue should not exist anymore?

**Comment by AlexFolland** [comment]
Oh, sorry.  This was still with the previous version.  I haven't tested with the latest due to the black screen bug (https://github.com/SWY1985/CivOne/issues/268).

**Comment by AlexFolland** [comment]
I've changed the name of this issue to describe the new software cursor issue.  There are many frames of input latency for me with the software cursor.  I am guessing this is caused by double buffering on top of the Windows compositor.  Triple buffering (lower-latency vsync method) in exclusive mode should reduce the latency, and single buffering (no vsync) is ideal with the Windows compositor.  Also, in exclusive mode, vertical sync completely disabled would be good for input latency, especially as tearing is nearly invisible in a static game like Civilization so vsync is unnecessary.

**Comment by AlexFolland** [comment]
I also think there might be other sources of input latency.  I notice when the game is in windowed mode, that I can move the cursor quite far before it snaps back, meaning it is only snapping into position every once in a while, which causes input latency.  Updating each frame internally might help.

**Comment by SWY1985** [comment]
Thanks for the explanation, this is very useful information.

**Comment by AlexFolland** [comment]
I've noticed that the cursor seems to update irregularly while on the same screen as a blinking unit.  The following linked video depicts this, but you have to look very carefully and the browser must have a good video renderer.  Firefox and Chrome are both known to have some vsync issues, but it looks smooth enough for me to see the issue using Firefox Nightly with e10s.  I would have uploaded the ~7.4MB video file to github, but github doesn't accept the mkv file extension.

https://www.youtube.com/watch?v=-dJioE8i-58

**Comment by SWY1985** [comment]
Thank you, I'll have a good look at it later.
Could you share the video on Onedrive, Dropbox, Mega or some other file sharing service?

**Comment by AlexFolland** [comment]
I uploaded it to my private server.  Here's the link: http://lex.clansfx.co.uk/requested/3CivOneissues.mkv

**Comment by SWY1985** [comment]
Thanks, I've got it, you can delete it again if you want.

**Comment by SWY1985** [comment]
This make me realise how much I'm looking forward to someone doing a 'let's play' of CivOne on YouTube...

**Comment by AlexFolland** [comment]
This is still not solved here, despite the big commit.  Sorry to say this!  I can see from the code how hard you worked on it.  I triple-checked that I was using the latest git commit and building from it, but it seems very much like it was before.  I can make a 60 fps video if you'd like, so you can see frame by frame what is happening.

**Comment by SWY1985** [comment]
OpenTK doesn't allow me to draw during a frame update, the screen, including the cursor, will just hang. I'm afraid this is as good as it's going to get for now.

**Comment by SWY1985** [comment]
For this issue I have opened #350 which I will pick up for the next version after this Milestone.
