### ISSUE TITLE
Show labels at the beginning of the game

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#271]
This is an unnecessary feature that is in Civilization.  For completion's sake, I'm dropping it here as a reminder.

![image](https://cloud.githubusercontent.com/assets/601517/23544499/213d2510-ffac-11e6-8cce-3a1c5a09d3ea.png)

Also, any time "hut" is used, "Village" should be used instead.

**Comment by SWY1985** [comment]
Yeah, I've got the screenshots in my todo archive but I'm not looking forward to this particular screen.
Might as well do it though. Thanks.

**Comment by AlexFolland** [comment]
I know what you mean.  It's a daunting feature to implement and doesn't add anything to the game for an experienced player.  It even slows down testing, so it would be good to add last.  It might be at least slightly less daunting if you notice that 3 of the labels ("Map Window", "Menu Bar", and "Active Unit") are always in the exact same spot, and the other 8 labels always indicate the top-most tile feature and are positioned on the exact same vertical row.

**Comment by SWY1985** [comment]
Thanks for the pointers. I've a good idea how this screen should be made, it's not going to take me more than an hour to create this.

**Comment by SWY1985** [comment]
I found (and fixed) a couple of other bugs I encountered along the way...
