### ISSUE TITLE
Attacking and conquering/invading an enemy city without City Walls does not reduce population

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#272]
I attacked and won a battle against an enemy city without City Walls of population 2 and its population was not reduced.  In Civilization, cities without City Walls are reduced in population when they lose a defending battle or are conquered.  If the population was 1, the city is destroyed.

**Comment by SWY1985** [comment]
I am aware of this. There was still a problem with capturing a city of size 1 (which reduces the city to size 0 and destroys it)... so I decided to leave it like this until I had the other issue solved. Will solve this issue soon.
