### ISSUE TITLE
If conquered enemy city has Palace, original Palace is destroyed

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#273]
Conquering an enemy city with a Palace in it destroys the original Palace.  In Civilization, conquering an enemy city with a Palace in it destroys the new Palace rather than the original.

**Comment by SWY1985** [comment]
This is a known issue, but I will solve it.

**Comment by AlexFolland** [comment]
Okay.  I've just doing a search here on GitHub issues for what issues are known and reporting ones I encounter that aren't present.  Please let me know if I can do anything better.

**Comment by SWY1985** [comment]
This is just perfect, please keep it up. It's no problem to report known issues that haven't been reported yet.
