### ISSUE TITLE
Changing build orders immediately after conquering enemy city is reverted once upon clicking "EXIT"

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#274]
Steps to reproduce:

1. Attack and conquer enemy city
2. Enter city screen
3. Change production to something that is not the same as what the city was producing
4. Click "EXIT"

At this point, the city screen does not exit and refreshes with the original production.  Changing production and clicking "EXIT" again works as usual.

**Comment by SWY1985** [comment]
I had this issue earlier in another situation, should be easy to fix.
