### ISSUE TITLE
After loading game, new cities' default names restart from first name

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#275]
I loaded a saved game from Civilization which already had "Moscow" and tons of other cities, built a new city, and it suggested "Moscow" again.  You can test it (and some other things probably) locally by loading this save.

http://lex.clansfx.co.uk/dump/civil0.map
http://lex.clansfx.co.uk/dump/civil0.sve

**Comment by SWY1985** [comment]
I wasn't aware of this yet, but it is linked to #153 
Load/Save games are not fully implemented and extremely buggy at the moment.
