### ISSUE TITLE
Cursor snaps and drags to game window when clicking outside while focused

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#276]
Steps to reproduce:

1. Alt+Enter to go fullscreen
2. Position cursor somewhere near the middle of the screen
3. Alt+Enter to leave fullscreen

This causes the cursor in Windows to be stuck far outside the game window while CivOne is still focused.

In my opinion, the game should not attempt to constrain the cursor to its window.  If that is desired, the user can use fullscreen mode.

**Comment by SWY1985** [comment]
That's a problem I have with OpenTK: I can not hide the cursor without capturing the mouse, so I created kind of a workable situation to overcome that. Thanks for the bug report.
A workaround (for now) is to use the Windows Native cursor. Go to settings, select Patches > Cursor Type > Native.

I will try to reproduce this and see if I can get a working solution.

**Comment by SWY1985** [comment]
I have created a (hopefully) better solution for the mouse enter/leave events. Can you please test this solution and let me know how it works for you?

**Comment by AlexFolland** [comment]
It is improved.  The cursor can leave the window.  However, left-clicking on something outside the window while CivOne is focused seems to act as if clicking and dragging from the click point to the nearest location inside the window.  With background browser text, that text becomes selected.  With the taskbar, the taskbar context menu appears, which also happens when clicking and dragging a taskbar button normally in Windows 7.

**Comment by SWY1985** [comment]
Obviously needs more work... thanks for your feedback.

**Comment by SWY1985** [comment]
Auto closed by commit comment... needs confirmation first...

**Comment by AlexFolland** [comment]
I just tested, and this issue is still present.

**Comment by SWY1985** [comment]
I'll have to test this in Windows 7 then... the problem does not exist in Windows 10.

**Comment by AlexFolland** [comment]
I found another way to reproduce it.  When the game is focused in windowed mode and the cursor is outside the window, pressing alt-tab and releasing causes the cursor to jump to the nearest point inside game window.

**Comment by SWY1985** [comment]
This still does not happen on Windows 10, but I should be able to test on Windows 7 soon. Hopefully I can reproduce it then.

**Comment by SWY1985** [comment]
This issue should be resolved with the new SDL version. Can anyone confirm it?
Binary download (64-bit only) is available here: https://www.civone.com/Download

**Comment by SWY1985** [comment]
I'm going to close this issue as it appears to have been fixed.

**Comment by AlexFolland** [comment]
Yup, confirmed.  This no longer happens here in the release build.
