### ISSUE TITLE
Some visual glitches in city production map

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#279]
Just below the city in the first pic and SW of city in the second pic:

![clipboard02](https://cloud.githubusercontent.com/assets/21365802/23588194/28178596-01ba-11e7-91db-781337730d95.png)
![clipboard04](https://cloud.githubusercontent.com/assets/21365802/23588195/28186344-01ba-11e7-97fb-14a7975a5482.png)

**Comment by SWY1985** [comment]
I thought this issue was solved, unfortunately I was wrong. I can reproduce this. Still haven't got a clue what's causing this.

**Comment by SWY1985** [comment]
I made some fixes and then played a couple of games and it hasn't happened again.

**Comment by SWY1985** [comment]
The issue has not been resolved, I'm reopening this issue.

**Comment by kazgaroth011** [comment]
Yes, it's still making white lines in the rivers.

**Comment by SWY1985** [comment]
I've made an attempt at fixing the palette issue with the City Manager, if it works correctly, I will also fix the other screens that have this issue. Needs testing...

**Comment by AlexFolland** [comment]
There is still a palette glitch here, at least.

![image](https://cloud.githubusercontent.com/assets/601517/23906202/871b3552-088a-11e7-9850-9a213db02d2f.png)

**Comment by SWY1985** [comment]
This hasn't been fixed yet, but if the City Manager works correctly now, I'll apply the same fix here.

**Comment by AlexFolland** [comment]
I don't see the palette glitches in city management screens, or remember seeing them recently.

**Comment by SWY1985** [comment]
Good, I'm going to commit changes that hopefully fixes this bug for all screens now.

**Comment by SWY1985** [comment]
Are the visual glitches solved?

**Comment by SWY1985** [comment]
Answer: No, there's still glitches.

**Comment by SWY1985** [comment]
I have found out what caused the glitches and solved it.
