### ISSUE TITLE
Small corrections to the savegame menu

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#283]
1) After the save is done, you should exit the menu after pressing a key:
![clipboard02](https://cloud.githubusercontent.com/assets/21365802/23588414/94d3734a-01bd-11e7-9f46-d86276aa7c84.png)

2) Saving the game should position you on the last saved location. E.g. if you saved the game on 3rd row, it should position you automatically on that row the next time you make a save. Also after you load the game it should position you automatically to 3rd row when you make a first save.

**Comment by SWY1985** [comment]
Linked to #248 
I also need to add a border around the save screen, and the background colour is incorrect.
