### ISSUE TITLE
Incorrect aspect ratio on non-8:5 displays (tested 16:9)

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#285]
Here is an example screenshot.  It is squished.  It also has extra padding at the bottom.

![image](https://cloud.githubusercontent.com/assets/601517/23592504/f7a61a2e-01b6-11e7-8d8f-5221facb732e.png)

Recommended solutions:

Use a scaling shader like pixellate.cg (https://github.com/libretro/common-shaders/blob/master/retro/shaders/pixellate.cg) (also has .glsl, .hlsl, and .slang (for vulkan) versions available) to accurately scale very similarly to nearest neighbor without compromising any sharpness.

or

Constrain scaling to integer scaling and use nearest neighbor.

**Comment by SWY1985** [comment]
You can change the settings by running Setup, go to Settings > Aspect Ratio.
I'm also working on expanding the game content beyond the original 320x200 pixels, but that is unfinished and unstable. (see #240)
