### ISSUE TITLE
No Factory graphic in city view

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#288]
![image](https://cloud.githubusercontent.com/assets/601517/23594295/d060cc04-01cd-11e7-9752-a4250921ac82.png)

![image](https://cloud.githubusercontent.com/assets/601517/23594296/d6e6cb78-01cd-11e7-9db0-8d46daeca43e.png)

**Comment by AlexFolland** [comment]
Same seems to apply to Manufacturing Plant.

**Comment by AlexFolland** [comment]
Hoover Dam also.

**Comment by SWY1985** [comment]
Not all buildings have been implemented, there's already a bug report for that: #32 
Here's a wiki page on the status of building rendering: https://github.com/SWY1985/CivOne/wiki/Status:-City-view-rendering

**Comment by AlexFolland** [comment]
Okay.  I'll keep that in mind.  Thanks for the info!

**Comment by SWY1985** [comment]
I've added Factory, MfgPlant, Nuclear Plant, SDI Defense and Recycling Center to the city view. :-)

**Comment by AlexFolland** [comment]
Sweet!  I am loving your work.  Great job!
