### ISSUE TITLE
Somehow a city got extra food without growing

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#289]
I'm not sure how this happened, but you can see the issue in this screenshot.

![image](https://cloud.githubusercontent.com/assets/601517/23594736/101a7ce8-01d1-11e7-831e-88fc49390bc1.png)

**Comment by SWY1985** [comment]
Please, if anyone finds out how to reproduce this, post it here.

**Comment by AlexFolland** [comment]
I think I've figured it out.  When you build a Settlers unit and there was another column of food storage, the food storage box is reduced in size and has the overflow of food remaining.

**Comment by SWY1985** [comment]
Great, I'll try to reproduce and then fix the issue.

**Comment by SWY1985** [comment]
Yes, that's it.
