### ISSUE TITLE
Transport is invisible

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#291]
There is a transport to the left of Cyrene in this screenshot.

![image](https://cloud.githubusercontent.com/assets/601517/23596940/d1a563e8-01e3-11e7-80ba-08e45306fed8.png)

Here's proof!  This Cavalry unit is walking onto the Transport unit.

![image](https://cloud.githubusercontent.com/assets/601517/23596943/d948c5f4-01e3-11e7-8569-b6645814725f.png)

This happened after my Settlers unit walked onto it there.

**Comment by SWY1985** [comment]
There's an issue with boats becoming invisible under certain conditions, I will try to fix it.
