### ISSUE TITLE
Under some unknown circumstances, city view in a new city is empty

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#292]
![image](https://cloud.githubusercontent.com/assets/601517/23597062/bda623f4-01e4-11e7-9662-636319dc199c.png)

Another city made in the same turn had the usual few buildings and roads in its city view.

![image](https://cloud.githubusercontent.com/assets/601517/23597085/eeb18556-01e4-11e7-816c-9b2f0d7fc014.png)

By the way, this civilization has learned all technologies quite a while ago, and still exhibits huts and teepees in city views.  Possibly another bug?

**Comment by SWY1985** [comment]
Rendering buildings in cities is experimental code and not finished, see these open issues: #32, #250
