### ISSUE TITLE
Apollo Program does not reveal cities

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#293]
The Apollo Program wonder's description says that it reveals all cities on the map, but it does not do so in CivOne.  In Civilization, it reveals each unrevealed city tile on the map, but nothing else.

**Comment by SWY1985** [comment]
Not all wonder effects have been implemented, and not all of them will be implemented yet, see this wiki page: https://github.com/SWY1985/CivOne/wiki/Status:-World-Wonder-Effects

**Comment by AlexFolland** [comment]
Okay!  Once again, thanks for the info.  I'll check out the wiki more before reporting issues related to unimplemented effects.
