### ISSUE TITLE
Some city screen graphics look kinda weird after a while

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#295]
The people in the top-left look weird, and some of the text is grey instead of white.

![image](https://cloud.githubusercontent.com/assets/601517/23598019/6baf42f8-01ec-11e7-8bd8-2e899cd6a07d.png)

**Comment by AlexFolland** [comment]
Several turns later, all the water has started looking weird.

![image](https://cloud.githubusercontent.com/assets/601517/23598248/0dad52c4-01ee-11e7-8d9d-6cb32fae1e78.png)

**Comment by AlexFolland** [comment]
Here's a repeatable color change.  I was able to swap between these 2 palettes by trying to irrigate here repeatedly.

![image](https://cloud.githubusercontent.com/assets/601517/23598420/232e8180-01ef-11e7-9aa1-4ce7539bf529.png)

![image](https://cloud.githubusercontent.com/assets/601517/23598426/3021ae94-01ef-11e7-8d9f-79ea18e21398.png)

**Comment by SWY1985** [comment]
Same as #279
