### ISSUE TITLE
Ironclad units not obsoleted by Cruiser units

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#297]
Ironclad's description says "Made obsolete by CRUISERS." but I can choose to make Ironclad units when I have access to Cruiser units.  I forget exactly what happens in Civilization in this case.  Are Ironclad units automatically upgraded to Cruiser units upon learning how to build them?  Are they all disbanded?  Do existing Ironclad units remain unchanged?  What about build orders involving Ironclad units?  I'm not sure.

**Comment by SWY1985** [comment]
The original game has no automatic upgrade mechanisms. Existing Ironclad units remain the same, cities building Ironclad units keep building them until the production is changed.

I will make the Ironclad unit obsolete upon the discovery of Combustion.
