### ISSUE TITLE
Some city settings revert each turn

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#299]
After changing entertainers to tax people or scientists, they are reverted to entertainers the next turn.  Also, after moving a worker's location, it is reverted the next turn.  This has caused Settlers units which were being supported by the moved worker to be lost.

**Comment by SWY1985** [comment]
There's some code in place to handle city resources, but it's not working correctly. It's affected by unit movement, but currently that means it will automatically correct city resources every time a unit is close to a city, which is nearly always.

**Comment by AlexFolland** [comment]
Something very weird happened.  This city was supporting a Trireme for a long time, even during Democracy.  The 1 worker was set to this location and remained there.

![image](https://cloud.githubusercontent.com/assets/601517/23830508/15074976-06c1-11e7-9eb1-60dcce8ed9d6.png)

Then suddenly, I got a message saying that Sevastopol could not support Trireme with the "Unit Disbanded." selection.  I then checked the city and it had moved the worker to this tile.

![image](https://cloud.githubusercontent.com/assets/601517/23830503/ef11c7e6-06c0-11e7-89bb-c53cc85ccf8d.png)

**Comment by SWY1985** [comment]
It's still a terrible fix for another issue: I've tried implemented relocating resources when enemy units move near the city and every time the city grows, but the algorithm is too aggressive and generally disappoints.
I'm going to completely recreate the entire logic behind this, I just need to figure out what I should replace it with. Give me some time... :-)

**Comment by AlexFolland** [comment]
The real question is, what does Civilization do?  According to what was posted in the thread, https://forums.civfanatics.com/threads/civ1-explained-city-disasters.507325/ , darkpanda on CivFanatics seems to be knowledgeable about reversing the game to figure out exact mechanisms.  It might be a good idea to ask them before deciding what to do.

**Comment by SWY1985** [comment]
There was a bug in my previous implementation, causing the game to check only valid tiles and relocate them, instead of checking the invalid tiles. I believe this has been resolved.
