### ISSUE TITLE
Display correct number of picture frames when choosing civs

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#306]
E.g. when you choose 4 civs it shows 5 frames as below:

![clipboard02](https://cloud.githubusercontent.com/assets/21365802/23675917/30b3aa96-037b-11e7-92b3-1b7dfeb3895c.png)

It should display 4. And 7 frames for 7 civs, etc.

**Comment by SWY1985** [comment]
I can't believe I never noticed this... thanks!
