### ISSUE TITLE
Having 3 trade should be equal to 2 gold & 1 science

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#307]
![clipboard15](https://cloud.githubusercontent.com/assets/21365802/23679899/a10a73a2-0389-11e7-8a7a-50d4cfa421a0.png)

It should be:
1 trade = 1 gold
2 trade = 1 gold + 1 science
3 trade = 2 gold + 1 science
4 trade = 2 gold + 2 science
5 trade = 3 gold + 2 science
...

**Comment by AlexFolland** [comment]
This depends on your tax rate.  Was it 50% at the time of this screenshot?

**Comment by SWY1985** [comment]
Confirmed, see below:

This is the original game, with 0.5.5:
![civ_036](https://cloud.githubusercontent.com/assets/9248547/23692236/b07adc48-03cd-11e7-9553-9759731773bf.png)

This is CivOne, with 0.5.5:
![image](https://cloud.githubusercontent.com/assets/9248547/23692250/c5d9034e-03cd-11e7-884e-e1feafbe694c.png)

Civilizations favours gold over science. I will fix this.
