### ISSUE TITLE
Implement tribal hut outcome

### ISSUE THREAD

**Issue by SWY1985** [SWY1985/CivOne#31]
The working of tribal huts is described by darkpanda here:
http://forums.civfanatics.com/showthread.php?t=510312

**Comment by SWY1985** [comment]
Need to implement Barbarian and Scrolls of wisdom events

**Comment by iStruggle** [comment]
I have yet to experience advanced culture (build city) but this could be chance.

**Comment by SWY1985** [comment]
It does, however, work... need to check the code, might be a bug
