### ISSUE TITLE
Game menu highlight and click region off by 1 vertically

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#311]
Civilization:

![image](https://cloud.githubusercontent.com/assets/601517/23690704/9d4ba59e-0378-11e7-9729-e47fa4c33242.png)

CivOne:

![image](https://cloud.githubusercontent.com/assets/601517/23690710/a7baab74-0378-11e7-8816-0989a394cabc.png)

Cursor is in the same position in both screenshots, and I'm running the latest git version.

**Comment by SWY1985** [comment]
I can reproduce this, it's an issue in the menu code, I will fix this.
