### ISSUE TITLE
Home city units' shield maintenance under Despotism

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#312]
In Civilization, the first 3 units home to a city do not require shield maintenance under Despotism.  Settlers require 1 food each, but the first 3 units do not require shields.  I've just tested to ensure my memory is correct.

![image](https://cloud.githubusercontent.com/assets/601517/23692317/95a337bc-0382-11e7-9a1e-fe7fe65eb548.png)
![image](https://cloud.githubusercontent.com/assets/601517/23692480/d6194e48-0383-11e7-822d-a8ac3adc5de2.png)
![image](https://cloud.githubusercontent.com/assets/601517/23692732/4ae0ba08-0385-11e7-932c-9e5045e11122.png)

In CivOne, I'm not sure what the situation is, but this Chariot has a shield cost and I'm guessing it should not.

![image](https://cloud.githubusercontent.com/assets/601517/23692287/7b89cee0-0382-11e7-8de8-d30348b41513.png)

**Comment by SWY1985** [comment]
I'm not certain if it's implemented correctly, needs to be checked, but in CivOne the implementation is as follows:

The first X units (excluding Diplomat and Caravan) do not require shield maintenance, where X is the city size. So in a city with Size 1, only the first unit is free.
Can you confirm it works that way, otherwise we'll have to figure out what I'm doing wrong.

**Comment by AlexFolland** [comment]
Oh!  It could be my mistake here entirely, never having noticed that it had to do with the city's population.  I'll do more testing and close this if it's invalid.

**Comment by AlexFolland** [comment]
I've just tested more, and it does appear to work that way.  My screenshots above do not disagree with that implementation also.  Closing this.  I'm sorry for the invalid reports lately.

**Comment by SWY1985** [comment]
No problem, please keep it up. It's no problem if I need to re-check the implementation.
