### ISSUE TITLE
Temple description wrong?

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#313]
I see this in Civilization.  It says 3 here.  Indeed, a Temple makes 3 unhappy people content.

![image](https://cloud.githubusercontent.com/assets/601517/23692881/38b5d2e0-0386-11e7-9947-5fe7d05e3a04.png)

This is in CivOne.  It says 2 here.

![image](https://cloud.githubusercontent.com/assets/601517/23692902/4fd5b346-0386-11e7-8544-3de1c72df0dd.png)

Maybe this is related to the version of Civilization that CivOne is based on.

I realize happiness is not yet implemented.

**Comment by SWY1985** [comment]
The descriptions are loaded from the text files included with Civilization. I believe you're using different versions of datafiles for the original game and CivOne. You can check for yourself in BLURB1.TXT, search for *TEMPLE2 and read the description:

![image](https://cloud.githubusercontent.com/assets/9248547/23693141/3b89d578-03d3-11e7-9104-83087fdf049b.png)

**Comment by AlexFolland** [comment]
You're right!  I grabbed the data files from a different installation.  I have 2 different versions of Civizilation.  One of them is in a folder called "CIV" and the other is in a folder called "CIV1ULTI".  I've been playing the one from "CIV1ULTI" because the other one has a game-breaking bug with new cities when many city improvements are learned.
