### ISSUE TITLE
Disable ground unit attacks from ships

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#320]
This message should appear:
![clipboard02](https://cloud.githubusercontent.com/assets/21365802/23770642/272fa192-0514-11e7-9236-a8a0a45d136f.png)

Unless the city is empty.

That's why we had marines in Civ2 :)

**Comment by SWY1985** [comment]
I have fixed this issue:
![image](https://cloud.githubusercontent.com/assets/9248547/23787855/4dadc76c-0574-11e7-9984-c40b3f636600.png)
