### ISSUE TITLE
Update the map when unit moves to 2 squares away from edge

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#321]
Like in this case below, currently in CivONE if the cruiser moves to within 1 tile from edge the map only then updates:
![clipboard04](https://cloud.githubusercontent.com/assets/21365802/23771071/e8c6e800-0515-11e7-925f-9f3e12282000.png)

It should update when it moves down to within 2 tiles in such a way, that the map first updates, and only then the unit moves.

**Comment by SWY1985** [comment]
This is only true for sea units with a view range of 2.
