### ISSUE TITLE
Some "spawn unit" bugs/enhancements

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#322]
1) When you spawn a unit it is invisible, only when you move with a map it becomes visible.

2) You cannot move a unit that you spawned on the same turn (could be a problem with a fighter).

3) Spawning a fighter gives a message "Your aircraft has run out of fuel ... " but does not delete it. Same with nuclear.

4) Disable spawning units inside _empty_ enemy cities. It gives weird results, the unit is inside the city, but the city does not belong to you.

5) Spawning land units on top of huts does not 'discover' the huts. They stay there if the unit moves out.

6) Disable spawning of units on dark portions of the map (or not. You decide).

BTW a really nice and helpful feature. Especially with the GO--> sign on top :)

EDIT: During spawning you can clearly see the graphical glitches on the map (like in #279 ). Perhaps this can be of help in reproducing the issue.

**Comment by SWY1985** [comment]
I'll consider these options, but I'm won't promise implementing all of them... (at once)

**Comment by SWY1985** [comment]
Okay, so I made some changes to the debug menu, most of your suggestions have been fixed:
1. Map becomes explored and the unit becomes visible immediately when spawning the unit
2. A spawned unit is able to move instantly
3. The aircraft message has been fixed (though it still appears for enemy units, that's a separate issue) 
4. You can no longer spawn units inside an enemy city
5. Huts get removed when you place a unit on top of them: There was no easy way to make it receive the goodies
6. Spawning on dark patches is still allowed. I will not disable it. You now instantly discover the dark tiles

You can now keep spawing the same unit with the right mouse button.

Additionally, I have added a dialog box with instructions on how to use the functionality:
![image](https://cloud.githubusercontent.com/assets/9248547/23787710/8d68b656-0573-11e7-9805-5457f8a9bcc8.png)

I assume this solves most of your suggestions?

**Comment by kazgaroth011** [comment]
Right clicking for multiple units is a winner!

In the latest version you uploaded I am still having issues with 1). After I spawn a unit it's invisible until I move with a map. BUT I noticed this happens only in portions of map where your active unit is not visible ! Activate a unit and move to some other location on a map where you can't see the active unit. Then spawn a unit and see what happens.

Other issues are solved.

**Comment by SWY1985** [comment]
I'll try to fix that too.

**Comment by SWY1985** [comment]
Yes, it's been fixed. :-)
