### ISSUE TITLE
Enemy units in the city appear as having city walls

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#324]
Attacking an enemy unit in the city without city walls gives the unit a black border (pic below), but this should be the case only when the city has city walls.

![clipboard02](https://cloud.githubusercontent.com/assets/21365802/23802732/7ebf1bae-05b4-11e7-9a6d-8167f0ebcbcf.png)

**Comment by SWY1985** [comment]
This is the same issue as #294

**Comment by AlexFolland** [comment]
How so?  This doesn't seem to be the same as that issue to me.  The other issue is about the unit appearing at all when attacking and losing the combat.

**Comment by SWY1985** [comment]
The unit in the city is becoming visible including its fortification, when it shouldn't. The unit fortification graphic is the same as the City Walls graphic, that's why it looks like the city has City Walls.
This issue will be solved once #294 is solved.

**Comment by AlexFolland** [comment]
They're still 2 completely different issues.  This one is about the unit being visible at all times and https://github.com/SWY1985/CivOne/issues/294 is about the unit not appearing during the attack animation when losing the attack.  I don't see how they're related.  It just doesn't make sense to me.  Anyway, it doesn't matter, if you say fixing one will solve the other.

**Comment by SWY1985** [comment]
For clarity, I'll reopen this issue until both are fixed.

**Comment by SWY1985** [comment]
This is a picture of a non-city wall attack on a city in the orignal game:
![image](https://cloud.githubusercontent.com/assets/9248547/23991323/2d526c24-0a39-11e7-90b4-291e12848e80.png)

The unit should be 1 pixel to the right and 1 pixel down, other than that the current behaviour is correct.

**Comment by AlexFolland** [comment]
Enemy units that win the combat are shown with "F" and without the city walls look, but with the city walls look when they lose the combat.
