### ISSUE TITLE
Implement "luxuries" people in the city management screen

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#325]
Probably already an issue but still... 

In the upper left corner when 1 resource is removed (Left=original Civ1, right=CivONE):
![clipboard02](https://cloud.githubusercontent.com/assets/21365802/23809461/17f260e2-05ce-11e7-8d2f-467208fa39a8.png)

When 2 resources are removed you should get a lady:
![clipboard04](https://cloud.githubusercontent.com/assets/21365802/23809462/181b2ff4-05ce-11e7-8188-a741272b3030.png)

**Comment by SWY1985** [comment]
Happiness and unhappiness will be implemented at a later time.

**Comment by SWY1985** [comment]
Moved forward to 0.1.0-alpha.1 because why not.

**Comment by SWY1985** [comment]
Happiness has been implementend.
