### ISSUE TITLE
Marketplace should also increase luxuries by 50%

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#326]
As it already does correctly with taxes.

Removing 1 resource (L=Original, R=CivONE):
![clipboard06](https://cloud.githubusercontent.com/assets/21365802/23809791/4c95713a-05cf-11e7-9fc0-d3d0b1c7e96c.png)

Removing 2:
![clipboard08](https://cloud.githubusercontent.com/assets/21365802/23809790/4c9536de-05cf-11e7-84f6-2e31e6ae0d5d.png)

Removing 3:
![clipboard10](https://cloud.githubusercontent.com/assets/21365802/23809792/4c9657a8-05cf-11e7-9515-ed6ae63ebb7a.png)

**Comment by SWY1985** [comment]
Thanks, I will implement this.
