### ISSUE TITLE
Hardware cursor visible while pointing at edge pixels

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#329]
While pointing at pixels at the edge of the screen, the hardware cursor is visible.  The following linked video portrays this issue.

https://www.youtube.com/watch?v=-dJioE8i-58

**Comment by SWY1985** [comment]
It's how the software cursor works right now. It's a difficulty with OpenTK and I'm going to try solving this at a later time.

**Comment by SWY1985** [comment]
The fix I wrote for #276 should also resolve this issue, can you please test it and let me know if this works for you?

**Comment by SWY1985** [comment]
I have tested this myself and I could no longer see the hardware cursor when pointing at the window edges. I consider this issue resolved.

**Comment by AlexFolland** [comment]
Yup, confirmed.
