### ISSUE TITLE
Railroad does not improve resource gains on tiles

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#331]
The railroaded and irrigated grassland tile in this screenshot should be providing 4 food under democracy, but is only providing 3.

![image](https://cloud.githubusercontent.com/assets/601517/23833247/30ab37b6-0700-11e7-93e3-e8d9130555c7.png)

This screenshot is to prove that it is grassland.

![image](https://cloud.githubusercontent.com/assets/601517/23833255/3ddf0980-0700-11e7-8b36-634320b4f293.png)

**Comment by AlexFolland** [comment]
The same is true on the plains tile in this screenshot.  It should be providing 3 food, but is only providing 2.

![image](https://cloud.githubusercontent.com/assets/601517/23833300/ab6a8182-0700-11e7-8719-8211ee378758.png)

**Comment by AlexFolland** [comment]
This railroaded mined coal hills tile should produce 7 production.

![image](https://cloud.githubusercontent.com/assets/601517/23833902/3600599e-070a-11e7-9008-4131ed662c6a.png)

According to this page, https://www.civfanatics.com/civ1/refcharts/civ1terchart.htm , railroad increases food and production on a tile by 50%, rounded down.  So, 2 more production from 5, 1 more food from 2 or 3, 2 more food from 4 (irrigated oasis).

**Comment by SWY1985** [comment]
I'm going to test this against the original game. If you find any more errors like this, please post them here.

**Comment by AlexFolland** [comment]
Mined hills should give 1 extra production, irrigated hills should give 1 extra food, etc.  Railroad's benefit, according to that chart, is this:

"Railroads increase food and resource production in a map square by 1/2 (rounded down). They increase trade by the same amount, but before the effects of Republic or Democracy governments."

That sounds right to me.

**Comment by SWY1985** [comment]
I had not implemented gains from RailRoads at all... so that's the reason.

**Comment by AlexFolland** [comment]
There seems to be some sort of error here.  A mined coal hills tile produces 5 production without a railroad.  With a railroad, it should produce 7 production.  Instead, it is producing 6.

![image](https://cloud.githubusercontent.com/assets/601517/23947903/e301fece-093d-11e7-8ef6-a1f748e22328.png)

**Comment by SWY1985** [comment]
With Anarchy and Despotism, the base value is 4 instead of 5:
![image](https://cloud.githubusercontent.com/assets/9248547/23949666/77cef77e-0988-11e7-896a-299833d2fbb2.png)

So 6 is correct in this case.

**Comment by AlexFolland** [comment]
My mistake then!  Thanks.
