### ISSUE TITLE
Buy values sometimes too high

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#332]
I don't know what causes this, but sometimes the buy values are not proportional to the number of shields required.  The SETI Program wonder should cost 4800 coins if you buy it on the first turn, then 4 times the remaining shields on subsequent turns.  It should never cost a value higher than 4800 with no shields or or 2396 with 1 or more shield.  Each shield costs 4 coins, or 8 if there are no shields.

![image](https://cloud.githubusercontent.com/assets/601517/23833436/d3bf8a40-0702-11e7-9576-824635f0c7cc.png)

**Comment by AlexFolland** [comment]
Here's another example.  A Factory requires 200 production to complete.  In this screenshot, I have built 80 shields, so 120 shields remain.  The buy value should be 480, but instead, it says 960.  In this case, it's exactly double what it should be.

![image](https://cloud.githubusercontent.com/assets/601517/23833530/81f215e6-0704-11e7-9fb9-cb2a24c006a0.png)

**Comment by SWY1985** [comment]
That's a bugger, I thought I had it all figured out.

**Comment by AlexFolland** [comment]
I might be wrong and buildings might cost double what units cost.  I was doing my calculation based on Settlers, which is a unit I buy very often in Civilization.  However, 17980 is beyond that anyway.

**Comment by SWY1985** [comment]
We figured it out here: https://forums.civfanatics.com/threads/buy-unit-building-wonder-price.576026/#post-14490920

I have either made a mistake in the implementation, or there's some extra rules that we didn't take into account.

**Comment by AlexFolland** [comment]
That formula looks non-linear.  The unit price formula may be non-linear, but the buildings formula is definitely linear.  Notice how every buy value is a multiple of 2 for non-wonder buildings and 4 for wonders.

Here is a pseudocode assignment for buildings:

price = ( totalShieldsRequired - currentShields ) * ( isWonder ? 4 : 2 )

I'm not sure about units.  Your current formula may well apply to them.  Tristan_C was right in that thread about buildings and wonders though.  CivOne is just incorrectly applying the units formula to buildings.
