### ISSUE TITLE
Moving from city built on top of railroad to railroad tile costs movement points

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#335]
In Civilization, if a city is built on top of a railroad, the railroad remains and moving from or to that tile from or to a railroad tile does not cost movement points.

**Comment by SWY1985** [comment]
Are you sure? I'm pretty sure you lose 1/3 moves after exiting a city.

**Comment by AlexFolland** [comment]
This is specifically a city built on top of a railroad; that is, one that already had a railroad on the tile before the city was built.  The city does not destroy that railroad tile and you get the full benefit from it.  The city only adds irrigation.

**Comment by AlexFolland** [comment]
I made a little demonstration video with one of my old saves.  It shows building a city on top of a railroad area, moving around on it without losing movement points, and that "RailRoad" is displayed in the tile information when the unit is on it.  The version depicted is 475.01.

http://lex.clansfx.co.uk/requested/CivOnerailroadcity.mkv

**Comment by AlexFolland** [comment]
Oh, the video also shows that the city tile gains the extra resources benefit from the railroad improvement, gaining 4 food per turn instead of 3.

**Comment by AlexFolland** [comment]
I noticed another component of this issue is that cities with railroad connected to them say "RailRoad" when a unit is standing on them, even if a railroad was not built on that tile before the city was founded.

**Comment by SWY1985** [comment]
It's an observation misinterpretation on my side, I'm looking at the best way to solve this... I believe the eventual solution will be less complex that the current implementation.

**Comment by AlexFolland** [comment]
I'm sure this would be solved with your simpler implementation, but I've just observed that another symptom is that a city with railroad built beside them that die leave railroad behind, even if no railroad was built there.
