### ISSUE TITLE
City screen stacking of trade conversion results hides excess light bulb icons

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#336]
The section that displays conversion of trade to coin and light bulb icons hides light bulbs after a certain point.  I made a video demonstrating this in a few cities.  At first, I thought it was a tax rate issue, but I figured out it was just way the icons were stacking.

http://lex.clansfx.co.uk/requested/CivOnetraderesultsstackingissue.mkv

**Comment by SWY1985** [comment]
Screenshots of how it's supposed to work are in this related issue: #258

**Comment by SWY1985** [comment]
Also related: #167

**Comment by kazgaroth011** [comment]
I've been studying for some time how all these icons in the upper-left corner stack. It's not that simple, especially with corruption.

I'll give you some results, just give me some time.

**Comment by AlexFolland** [comment]
No hurry.  This is a very unimportant issue imo.

**Comment by SWY1985** [comment]
I will try to get it fixed this week.
@kazgaroth011  Any screenshots you can provide are very much appreciated, thank you!

**Comment by kazgaroth011** [comment]
No problem, I wouldn't be doing this if I wasn't enjoying.
I'll provide screenshots, as with the food storage stuff.
