### ISSUE TITLE
Regression: Enter doesn't work on autosave screen

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#343]
Pressing main enter or numpad enter saves the game here, but doesn't continue to the next screen.  See the stdout log in this screenshot.

![image](https://cloud.githubusercontent.com/assets/601517/23900248/a31ee25e-0875-11e7-8eea-9f4bfe92e579.png)

**Comment by SWY1985** [comment]
That's strange, it works for me and I tested this really well.
Don't you get a save confirmation dialog?

**Comment by AlexFolland** [comment]
This appeared at 2000 BC and what you see in the screenshot is what I saw.  Pressing enter made that line appear in stdout, but nothing else.  Pressing escape exited this screen back to the game.

**Comment by AlexFolland** [comment]
For the record, I was using 9aa6d07070eacfd79f3139601cd13ee17abcb808 in this screenshot.

**Comment by AlexFolland** [comment]
I will tell you if it happens again, also, and try to give more detail in that case.

**Comment by AlexFolland** [comment]
It could have something to do with "End of Turn" being enabled.  I always enable it, and I noticed that it is disabled by default.

**Comment by AlexFolland** [comment]
Yeah, it happened again at 1000 BC, and I definitely have "End of Turn" enabled.  I can't think of any other details to mention.

**Comment by SWY1985** [comment]
Can you set breakpoints in /src/Screens/SaveGame.cs at lines 97, 120, 169, 191 and and see if any of them are ever hit. If so, please make a screenshot of VScode.

**Comment by AlexFolland** [comment]
I'm running without debugging, as running with debugging doesn't work here.

**Comment by SWY1985** [comment]
Ah... okay.
Does saving via the game menu work for you?

**Comment by AlexFolland** [comment]
If the stdout lines are correct, yes, but no, pressing enter while the file I want to overwrite is highlighted doesn't do anything.

![image](https://cloud.githubusercontent.com/assets/601517/23906815/5d62377c-088c-11e7-8e60-51d844d9b608.png)

**Comment by SWY1985** [comment]
I have tried running the game on Windows 7 still can't reproduce this issue.

**Comment by AlexFolland** [comment]
It worked previously, so it must be something that was changed.

**Comment by SWY1985** [comment]
There's a change: I have added a confirmation dialog.
I'm going to keep trying to find out what could cause this...

**Comment by SWY1985** [comment]
I can finally reproduce this...

**Comment by SWY1985** [comment]
Is this possibly related to the invalid save games?

**Comment by SWY1985** [comment]
There's been some more fixes to the Save games, including data validation on existing save games.
The one situation where I could reproduce this had to do with corrupt save games. This appears to have been solved.
Can you test to see if it works now? If not, can you try saving to another 'drive letter'?

**Comment by AlexFolland** [comment]
I can't test this adequately until https://github.com/SWY1985/CivOne/issues/384 is resolved.

**Comment by AlexFolland** [comment]
This seems to be fixed.

**Comment by SWY1985** [comment]
Great news, thank you for testing! 👍
