### ISSUE TITLE
Software cursor image visible but missing during pre-menu intro; square shown instead

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#349]
The square in this image is the cursor.

![image](https://cloud.githubusercontent.com/assets/601517/23941096/c9613cfa-0924-11e7-9684-f38a1cd87bca.png)

**Comment by SWY1985** [comment]
I can reproduce this, didn't have this problem because I started the game in Setup mode.
The problem is that no cursor should be visible in this screen, but it is rendered anyway. Should be easy to fix.
