### ISSUE TITLE
Prevent game freezes by moving actions in background threads

### ISSUE THREAD

**Issue by SWY1985** [SWY1985/CivOne#350]
Sometimes the game hangs because it is busy, and the screen (including the mouse cursor) hangs.
This could be solved my moving slow tasks to a background thread.

**Comment by AlexFolland** [comment]
Might it be useful to call System.Threading.Thread.Sleep(1) in the main loop, to prevent busy-waiting?  Are there slow tasks to do while idle, or is it doing them extremely quickly, but many times unnecessarily?

**Comment by SWY1985** [comment]
The main loop is handled by OpenTK, with update events being called every 1/60th of a second. The problem is that there's certain moments that these updates take too long to fit in 1/60th of a second.
Added Sleep(1) won't fix the problem, as the game is actually busy.
Putting heavy tasks into seperate background threads might be a good solution. Another solution could be handling heavy tasks over multiple update moments.

**Comment by AlexFolland** [comment]
I don't understand what it could be busy with while idly waiting for user input.  Civilization takes almost no CPU while idle.  There should be no heavy tasks, except once in a while, between turns or movements.  I will have to take a good look at it myself some time.

**Comment by SWY1985** [comment]
I have just moved the mouse position update code to the Render event. It appears to make the cursor lag less. Can you try it?

**Comment by AlexFolland** [comment]
Sure!  I'll do so when I next update, after this game.  I have been avoiding updating during games since they lose all progress currently.

**Comment by SWY1985** [comment]
I'm hopefully able to fix load/save games this weekend...
