### ISSUE TITLE
Fully upgraded Oasis tile gives 4 food instead of 6

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#356]
Here is the Oasis tile in question.  It has "RailRoad" and "Irrigation".

![image](https://cloud.githubusercontent.com/assets/601517/23975740/f9f0dba2-099f-11e7-8917-a5d3cea050ce.png)

This tile is only giving 4 food instead of 6.  The government is Democracy.  Such tiles in Civilization give 6 food.

![image](https://cloud.githubusercontent.com/assets/601517/23975754/2221d004-09a0-11e7-92bd-baa60771d0f8.png)

Here's a screenshot from Civilization showing a fully upgraded Oasis giving 6 food.

![image](https://cloud.githubusercontent.com/assets/601517/23976357/58fdf310-09a4-11e7-9ee6-bfcd130b2357.png)

**Comment by SWY1985** [comment]
Related to #354, I'm going to re-check all terrain bonuses.
