### ISSUE TITLE
End-game sequence didn't appear upon conquering all enemy civilizations

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#358]
I was unsure if I'd conquered every civilization, so I made sure to explore the entire world map to find any enemy cities.  There were no enemy cities left, yet the end-game sequence never started.

![image](https://cloud.githubusercontent.com/assets/601517/23981722/1478f65a-09c6-11e7-98a1-2787163ff2a7.png)

The year in this screenshot is 20 BC.  It was somewhere around 500 BC that I conquered the last enemy city.  I'm not sure exactly when though.

![image](https://cloud.githubusercontent.com/assets/601517/23981773/6f672136-09c6-11e7-88f5-86b2b223abff.png)

**Comment by SWY1985** [comment]
There was a condition where cities of size 0 (destroyed cities) were still counted as cities owned by a certain player. This caused a failure to detect whether a civilization was destroyed. This condition has been fixed.
