### ISSUE TITLE
Determine correct stacking in the 'city resources' window

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#360]
I've written about some of my findings in the document below. Hopefully you can open it, otherwise I will prepare it in a different format. Writing about all this in Github would be much harder.

[Stacking.docx](https://github.com/SWY1985/CivOne/files/851031/Stacking.docx)

I don't know how much of this has already been implemented in CivONE, since I cannot download the newest version from Civfanatics.

**Comment by SWY1985** [comment]
Why can't you download the game from CivFanatics? The download links work for me:
- (32 bit) http://www.civone.com/files/civone-0.1.0pre-alpha1-r1023-winx86.zip
- (64 bit) http://www.civone.com/files/civone-0.1.0pre-alpha1-r1023-winx64.zip

Stacking is mostly implemented like the document you posted... except I made sure that the resources don't overflow onto the map and the shields can stack in CivOne.

**Comment by SWY1985** [comment]
I'm going to have a good look at your document so I can make more fixes to the CivOne logic where needed. Thank you very much!

**Comment by kazgaroth011** [comment]
OK, the link works now, don't know what happened.

**Comment by SWY1985** [comment]
How is the stacking in the current version?

**Comment by kazgaroth011** [comment]
I've tested it just now on a large city and the stacking appears to be working ok. You can close the issue, if anything shows up I'll mention it.

**Comment by SWY1985** [comment]
Thank you. :+1:
