### ISSUE TITLE
With Colossus the city itself should have +1 trade

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#361]
Left=original, right=CivONE:
![clipboard02](https://cloud.githubusercontent.com/assets/21365802/24056458/0944ffc0-0b44-11e7-9b3a-c0dc70753f26.png)

**Comment by SWY1985** [comment]
You're right, I didn't apply the bonus to the city tile.

**Comment by jakebrown58** [comment]
nice find.

**Comment by SWY1985** [comment]
On what tile is the city, or can you send me a save game. I can not reproduce this yet.

**Comment by AlexFolland** [comment]
I can tell from the screenshot that it's a River tile without a shield or a railroad.

**Comment by SWY1985** [comment]
You're right... I didn't sleep well and I wasn't paying attention. ;-)
I'll look into it.

**Comment by AlexFolland** [comment]
No worries.  I was just trying to help!  :)  You are doing a great job.  I hope you can sleep well soon.

**Comment by SWY1985** [comment]
Solved....

![image](https://cloud.githubusercontent.com/assets/9248547/24075910/491cf9e0-0c25-11e7-8701-41849e832e1b.png)

**Comment by SWY1985** [comment]
Can anyone confirm it works correctly now?

**Comment by kazgaroth011** [comment]
Yes it's ok now.
