### ISSUE TITLE
Irrigation and roads in generated map

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#363]
I had just started the game and found irrigation and roads in the generated map.  There was even a village on one of the irrigated tiles.

![image](https://cloud.githubusercontent.com/assets/601517/24061008/f37001f8-0b12-11e7-983b-3364bd0166e6.png)

I'm fairly certain I've never seen this happen in Civilization.

I found mining too.

![image](https://cloud.githubusercontent.com/assets/601517/24061225/cc5c8f68-0b13-11e7-8abc-9bd78d29e606.png)

**Comment by SWY1985** [comment]
I had a game start like this too, once, and I haven't got a clue what's causing it.

**Comment by AlexFolland** [comment]
How are the maps generated?  It's possible that it also happens in Civilization if the generation algorithm was copied.  More testing in the original game might be prudent.

**Comment by SWY1985** [comment]
This has nothing to do with the original map algorithm. I'm 100% certain the original game never places any map improvements during generation.

I suspect this to be a problem where the AI player get to play the game before it's started, although I have no idea how it happens and why it doesn't happen most of the time...

**Comment by SWY1985** [comment]
I know this can happen but I can't reproduce it. If anyone finds out under what conditions this happens, please let me know.

**Comment by AlexFolland** [comment]
Perhaps adding a way to provide the game a random seed and extract the map's seed from a save file would be a good way to diagnose this.

**Comment by SWY1985** [comment]
That's a good idea, I'll look into that, thanks.

**Comment by AlexFolland** [comment]
I think I would have to reproduce it again, but at least I would be able to provide a seed if I did so.

**Comment by SWY1985** [comment]
I just noticed that the seed is stored in the save file, so the next time this happens, could you save the game and post it here? I'll be able to extract the terrain seed and try to reproduce it.

The random seed thing is still a good idea and I'm going to steal it. ;-)

**Comment by AlexFolland** [comment]
Apparently I still have some autosaves from this game.  I still can't manually save the game due to the other issue.

Some of these saves won't allow me to load them.  Only the 3000 BC one lets me load it.  This may be another new issue I hadn't yet encountered.  I'll open a separate ticket.

GitHub won't let me upload the file, even though it claims to support zip files.  There are so many issues everywhere.  Anyway, here you go.

http://lex.clansfx.co.uk/requested/CivOnesomeunloadablesaves.zip

**Comment by SWY1985** [comment]
Thanks... load/save games have not been fixed yet, I tried to relax a bit last weekend.
The save games, unfortunately, do not store the random seed but only the last (or first) 4 bits of the initial random seed, so I can not find out the random seed.

**Comment by SWY1985** [comment]
I never have this happen to my games anymore, after the recent fixes.
There was a problem where, at the game start, some players got an unreasonable amount of turns before building their first city. This issue has been resolved so I believe I can close this issue.

**Comment by AlexFolland** [comment]
Sounds good!  It can be reopened if the issue is seen again.  Thanks a lot!
