### ISSUE TITLE
Railroad visible between adjacent cities before the discovery of Railroad

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#364]
![image](https://cloud.githubusercontent.com/assets/601517/24061188/aa43772a-0b13-11e7-8d43-03340880e5ed.png)

**Comment by SWY1985** [comment]
This is correct behaviour, I'll post a screenshot of the original when I get home.

**Comment by AlexFolland** [comment]
I believe you.  I'll close it.
