### ISSUE TITLE
Railroaded Hill and Mountain tiles with railroad stop movement from railroad tile when unit has low movement points

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#366]
My unit had "0.2" movement points left and was standing on a railroaded Hills tile.  I attempted to move onto an adjacent railroaded Hills tile, which should not cost movement points, but my unit lost its turn.

**Comment by AlexFolland** [comment]
I just tried to reproduce it and found that it doesn't always happen.  I don't know what causes it.

**Comment by AlexFolland** [comment]
Wow, I just reproduced it with a Settlers unit, but then did the exact same thing with another Settlers unit the next turn and didn't reproduce it that time.  Bizarre.

**Comment by AlexFolland** [comment]
Okay, I can reproduce it by walking from a road tile to a railroaded mountain tile, getting "0.2" movement points, then moving back and forth between 2 railroaded mountain tiles.  At a seemingly random point, the movement will be stopped.

**Comment by SWY1985** [comment]
I think the terrain penalty is somehow involved when it shouldn't be. There's a random factor in that...
