### ISSUE TITLE
Strage bug - game freezes but I can use the menus

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#377]
During this game during enemy turns the game seemed to go into and endless loop (the colored rectangle in the bottom left corner kept changing). I couldn't go into cities but I could still use all the menus (orders, advisors, world, etc.). Also I couldn't move on the map, but the minimap still kept updating. This happened to me once before.

![clipboard04](https://cloud.githubusercontent.com/assets/21365802/24209918/c7546c6c-0f27-11e7-8acd-52de6d2fe99f.png)

**Comment by SWY1985** [comment]
There was a bug in the AI code, making the AI retry an impossible turn forever. This issue has already been fixed here: 4ff0aed62482497cfebbabeaf3bd0d60f5db8519
