### ISSUE TITLE
Decrease distance between people figures in the city menu

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#378]
left=Civ1, right=CivONE
![clipboard08](https://cloud.githubusercontent.com/assets/21365802/24210994/0b1cc888-0f2b-11e7-818b-650cc05eae5d.png)
![clipboard10](https://cloud.githubusercontent.com/assets/21365802/24210995/0b46519e-0f2b-11e7-8dc4-ea73a0ad8c4f.png)

Consequently pressing directly on the singer guy to change to taxman/scientist doesn't work, I have to press a bit to the left.

**Comment by SWY1985** [comment]
Thanks for the screenshots, very helpful.
