### ISSUE TITLE
A lot of "dotnet" crashes happening recently

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#381]
Here's an example if it's of any help:

![clipboard04](https://cloud.githubusercontent.com/assets/21365802/24272504/e8101374-101d-11e7-9cff-423683fbe237.png)

**Comment by SWY1985** [comment]
This helps a lot, please keep reporting the crashes in seperate issues for every situation that crashes the game and I'll be able to fix the bugs.
The console window tells me exactly where the error occured so that should be easy to fix.

**Comment by SWY1985** [comment]
It appears the attack code got called in the code above, while no unit was present at the location. Do you have any idea how this happened?
I've created a code change so this shouldn't happen again in future builds.

**Comment by kazgaroth011** [comment]
I don't remember for this case. Will be more alert in future crashes.
