### ISSUE TITLE
Border graphical corruption

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#385]
I'm not sure what caused this.  I will let you know if I find out.

![image](https://cloud.githubusercontent.com/assets/601517/24300153/bb5a54f2-1068-11e7-8353-c1b55507f3f9.png)

**Comment by SWY1985** [comment]
Does this happen every time? I've been testing loading/saving all day and I haven't ever seen this...

**Comment by AlexFolland** [comment]
I have no idea.  I have also seen it in other screens.

![image](https://cloud.githubusercontent.com/assets/601517/24300293/35ac8de2-1069-11e7-8d45-fbcfa4ac095d.png)

**Comment by AlexFolland** [comment]
It doesn't happen every time.  In the Civilopedia, clicking Hills, leaving, clicking Hills, etc. shows either no border or this corrupted border seemingly randomly.

![image](https://cloud.githubusercontent.com/assets/601517/24300332/5afc2922-1069-11e7-8cac-b849f5de758d.png)

**Comment by SWY1985** [comment]
This shouldn't happen... I will look into this.

**Comment by SWY1985** [comment]
I now have the same issue... working on a solution.

**Comment by SWY1985** [comment]
This issue has been solved with my recent graphics/sprites rewrite.
