### ISSUE TITLE
Hide mouse (torch) during enemy turns

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#388]
Also I can enter cities and move through map during turns. While a nice feature, this does not happen in Civ1.

**Comment by SWY1985** [comment]
That's true, I will hide the mouse cursor when the enemy is moving.

**Comment by AlexFolland** [comment]
The cursor is also hidden while a player unit is moving, though that might be considered a separate issue.

**Comment by SWY1985** [comment]
I'll pick that up at the same time.
