### ISSUE TITLE
Game crashes after enemy unit moved

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#389]
The blue enemy horseman moved, after that the game crashed:
![clipboard01](https://cloud.githubusercontent.com/assets/21365802/24302880/6e78c474-10b4-11e7-9984-5d93cde85453.png)

**Comment by SWY1985** [comment]
This may have been solved already... but I'll keep this issue open until I'm sure.

**Comment by SWY1985** [comment]
The issue was caused by an enemy unit GoTo action being blocked by an enemy unit. This issue has been resolved.
