### ISSUE TITLE
After conquering enemy city the square is still occupied

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#399]
An enemy chariot was on the red square. After I occupied the city the chariot disappeared but the square is still marked red.
![clipboard03](https://user-images.githubusercontent.com/21365802/29227038-945f1cd6-7ed4-11e7-92b0-8c2439d3207c.png)

**Comment by SWY1985** [comment]
Are you sure the square is not occupied by another city?
I'll try to reproduce this.

**Comment by kazgaroth011** [comment]
Yes I was just thinking about this yesterday after I posted the issue. Close this one, if it turns up again we'll open it.
