### ISSUE TITLE
Two smaller animation issues

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#400]
Not that important but still:

1) The animation when attacking an enemy unit is a bit off. After you attack your unit slowly starts moving toward the enemy and only then does the attacking animation appear. This movement should at least be faster I believe.

2) When attacking an empty enemy city (size=3), the city size first turns to 2 and only then is the movement animation done.

Some of these problems become more noticeable because of the lag in the game.
I can't remember if this issues were opened up in the past.

**Comment by SWY1985** [comment]
Right now, I'm working on optimizing the game map drawing code and the animations are completely broken. I will make sure to implement the attack animations correctly this time.

**Comment by SWY1985** [comment]
I believe both points have been addressed correctly. Can I close this issue?

**Comment by kazgaroth011** [comment]
It's OK now.
