### ISSUE TITLE
Change text color for 2 lines in the Orders menu

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#402]
Irrigation should not be enabled if settler is not next to water.
Fortress cannot be built before construction is researched.

Original Civ1:
![clipboard10](https://user-images.githubusercontent.com/21365802/29227757-6694a8fe-7ed7-11e7-911e-ddaa6a311e9e.png)

CivOne:
![clipboard08](https://user-images.githubusercontent.com/21365802/29227758-66bb5a76-7ed7-11e7-9717-91c8bba7fa6a.png)

**Comment by SWY1985** [comment]
Good point, I'll fix this.
