### ISSUE TITLE
Map tile not discovered when unit moves on map edge

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#429]
When unit moves close to the screen edge, the map tile isn't discovered (it does so when you move mouse).

![issue](https://user-images.githubusercontent.com/21365802/32911267-fd8f3b18-cb0b-11e7-8853-2385baccb994.PNG)

**Comment by SWY1985** [comment]
This is a side effect of the new map drawing code. I'll fix it.
