### ISSUE TITLE
City improvements are not fully visible

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#431]
As with hanging gardens here:
![capture2](https://user-images.githubusercontent.com/21365802/32959314-8ada67e4-cbc1-11e7-95e2-b5d587031dc3.PNG)
EDIT: When I build Copernicus observatory, it's not visible at all!

**Comment by SWY1985** [comment]
This is a known issue, and I'm planning to implement it along with issue #32.
