### ISSUE TITLE
Enemy city appears out of nowhere and then disappears

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#434]
Immediately after discovering an arctic tile an enemy city appeared out of nowhere on this tile and then quickly disappeared.

**Comment by SWY1985** [comment]
I can not reproduce this yet...

**Comment by kazgaroth011** [comment]
Yes it happened just once, but it definitely happened.

**Comment by SWY1985** [comment]
I know how to reproduce this now.
