### ISSUE TITLE
A strange issue when changing to monarchy

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#436]
When I change from despotism to monarchy I get a bunch of "this city cannot support unit" messages. One of my cities (size 4) cannot support even a single unit. I'll try to compare this with original.

**Comment by SWY1985** [comment]
I noticed this too when I switched to Democracy. Not sure what happened, but there's definitely something wrong here.

**Comment by AlexFolland** [comment]
I think cities support non-caravan/non-diplomat units up to their population limit for free in Despotism, but cost a shield each in Monarchy and Democracy.

**Comment by SWY1985** [comment]
I believe this is currently implemented as such, or has something gone wrong?
Can someone confirm there's something wrong with the current unit costs implementation, because I couldn't find anything (yet).

**Comment by SWY1985** [comment]
Can we confirm that this is a bug and steps to reproduce it?
I'm checked and it seems to work correctly...

Moving to alpha.2 milestone.

**Comment by AlexFolland** [comment]
I believe this is working as intended because cities support non-caravan/non-diplomat units up to their population limit for free in Despotism, but cost a shield each in Monarchy and Democracy.  If a city has no shields in Monarchy and Democracy, it can't support any non-caravan/non-diplomat units.

**Comment by SWY1985** [comment]
Thank you. I'm going to close this issue. If we find any proof that something is wrong, we can reopen it or make a new issue.
