### ISSUE TITLE
Enemy civ on 2 continents (Earth map)

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#439]
On earth map (playing as Americans) just a few turns into the game I encountered French city on my continent even though they are also in Europe. Is it possible 2 settlers spawned for French at the beginning of the game, each on its own continent?

**Comment by SWY1985** [comment]
That should not happen. I will try to reproduce it.

**Comment by SWY1985** [comment]
I think I've started over a hundred games on earth. I couldn't reproduce it. Then, I modified the code so all civs always start with 2 settlers. Again, this didn't happen. Following the code, this situation should be impossible. Please, if it happens again, could you make a save game (broken as it is) and send it to me?

**Comment by SWY1985** [comment]
Sorry, after re-reading, I tried starting as American. The first time, this exact situation happened. I can reproduce it now.

![image](https://user-images.githubusercontent.com/9248547/32988505-72573a62-cd06-11e7-92b8-e001f2e3cce5.png)

**Comment by SWY1985** [comment]
It get stranger... another game started as American, the Germans have another city on the exact same spot, with size 2. That means they started with 3 Settlers. The Aztecs also have another city on Cuba.
Something is very, very wrong here.

**Comment by SWY1985** [comment]
I had a city size 8 on the continent, along with a couple of warnings that a settler could not be added to a city of size 10 or higher. When I entered the city in cheat mode, the player had not discovered the tiles of the city, so it couldn't get any resources. That's why the city disappears after a while. This bug is related to #434

**Comment by kazgaroth011** [comment]
Yes I also had Aztecs in Cuba, but they were not present in the American continent. Orleans was 1 or 2 tiles to the left as shown in your picture.
