### ISSUE TITLE
Huts appear on irrigation tiles

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#440]
This is most likely an issue with loading the game.
![capture4](https://user-images.githubusercontent.com/21365802/32982809-9b52c688-cc8a-11e7-8a37-7796c3ee88ab.PNG)

**Comment by SWY1985** [comment]
Yes, known issue, it has to do with loading games:
The original game keeps track of all the tiles that have been visited by any unit. If a tile has been visited before, the hut is removed. This mechanism is not yet working in CivOne. Will fix in #153
