### ISSUE TITLE
A couple more animation issues

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#443]
- when leaving a city with a chariot in the first turn the city is emptied but it's still indicated as being occupied by a unit (this is updated only after the second move)
- similarly when leaving a city (which has other units) with a chariot, in the first turn you move out the city has a visible fortified unit (as in the pic below), but it shouldn't
![capture5](https://user-images.githubusercontent.com/21365802/33027597-d21898e8-ce13-11e7-82a4-f39636808c91.PNG)

**Comment by SWY1985** [comment]
These issues have been resolved. CivOne unit animations now work the same as the original game.
