### ISSUE TITLE
2 issues with destroying enemy civ message

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#446]
The message should be displayed immediately after I destroy enemy civ (it was now displayed only after the end of turn).
Also I was playing Egyptians and the message I got was "Zulu civilization destroyed by barbarians" (this happenrd only once).

**Comment by SWY1985** [comment]
The current implementation is half-baked. After capturing a city, the game should check who destroyed the civ and show the message but it doesn't work correctly. It also doesn't check after destroying a unit. I will review this code.
