### ISSUE TITLE
Advance picture flashes in negative when advance screen fades

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#450]
As title, on the "wise men discover" screen, all displays correctly until after the advancement description screen. As the screen fades, the advancement image inverts colours.

**Comment by SWY1985** [comment]
The palette for the civilopedia screen is a merged palette of two PIC files. The screen fade out code uses the original colours of the default palette, unmixed with the Advance Picture palette. That's why the colours change.
I've made a solution for this.
