### ISSUE TITLE
Opening scene runs a bit too fast

### ISSUE THREAD

**Issue by lempamo** [SWY1985/CivOne#451]
The opening scene with the credits and title card runs a bit faster than the original DOS version.

**Comment by SWY1985** [comment]
I'm going to have to compare it with the original game to get the timing right.

**Comment by SWY1985** [comment]
I'm not sure that the Dosbox speed is correct either... I've implemented a slight delay though, seems to be more or less correct now.

**Comment by SWY1985** [comment]
Can you please try the latest version? Has this issue been resolved?

**Comment by lempamo** [comment]
Yep
