### ISSUE TITLE
Is Gandhi Nuke-Happy in this version of Civ?

### ISSUE THREAD

**Issue by lempamo** [SWY1985/CivOne#454]

**Comment by SWY1985** [comment]
AI has not been implemented, there's just an abstraction of an AI at the moment with mostly random moves. Yes, Gandhi will be Nuke-happy in this version of Civ, as he should, and yes, there will probably be plugins to disable this 'bug'.
The development of CivOne is currently not at a stage where AI features are being developed, so I'm going to close this issue. I hope I have answered your question.
