### ISSUE TITLE
Activated fortified units in a city should not be shifted to the right

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#455]
Selecting & activating units on the left moves them to the right side. This should not happen.

![image](https://user-images.githubusercontent.com/21365802/34393254-7d8e30d4-eb51-11e7-98f4-8384bd3e1683.png)

**Comment by SWY1985** [comment]
Thank you, I will fix this today.

**Comment by SWY1985** [comment]
The original game orders the units by internal id.
