### ISSUE TITLE
City names invisible when building a new city

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#474]
![capture2](https://user-images.githubusercontent.com/21365802/38429117-c7297c84-39bd-11e8-8a3e-b5ecc9f6abec.PNG)

Also when choosing a leader name in the beginning of game:
![capture1](https://user-images.githubusercontent.com/21365802/38429116-c704b71e-39bd-11e8-86aa-022c69287b42.PNG)

**Comment by SWY1985** [comment]
Thanks for the bug report.
This probably has something to do with recent changes to the input box. I'm on it. 👍
