### ISSUE TITLE
Game freezes when loading a saved game

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#475]
I can see the unit blinking in the minimap but the main window is frozen.

**Comment by SWY1985** [comment]
Does this happen with all save games, or only some? Can you attach a save game file?

FYI: You can access your save games by typing this in the Explorer address bar: %LocalAppData%\CivOne\saves

**Comment by kazgaroth011** [comment]
It happens with all games. Here are last two.
[c.zip](https://github.com/SWY1985/CivOne/files/1885077/c.zip)

**Comment by SWY1985** [comment]
Thank you.
