### ISSUE TITLE
Game Crashes when barbarians cannot find a tile to start an invasion.

### ISSUE THREAD

**Issue by mattitk** [SWY1985/CivOne#483]
![civone_crash](https://user-images.githubusercontent.com/22025648/38768910-33883f3c-4003-11e8-81d1-838ba5441179.png)

The turn indicator started blinking in white and gray and the game froze.

**Comment by SWY1985** [comment]
I have created a fix for this. When the barbarian ship finds all land tiles are occupied by land units, it will attack with the ship instead.
