### ISSUE TITLE
Color glitches in Intro screens

### ISSUE THREAD

**Issue by darkpandaman** [SWY1985/CivOne#5]
Several of the Intro pictures are keeping "background magenta" visible when displaying. Attached are a few samples

![0](https://cloud.githubusercontent.com/assets/7324000/7721581/6760c48c-ff0b-11e4-99a8-bfd14782df4a.png)
![1](https://cloud.githubusercontent.com/assets/7324000/7721580/675c3ffc-ff0b-11e4-9027-64540eb05ccf.png)

**Comment by SWY1985** [comment]
This bug is introduced while trying to fix a Linux issue, I'll fix it.

**Comment by SWY1985** [comment]
I've created a workaround, the colour glitches should be gone now (on Windows), I will create a definitive fix later.
