### ISSUE TITLE
After playing for a while, the game can crash

### ISSUE THREAD

**Issue by SWY1985** [SWY1985/CivOne#57]
Process is terminated due to StackOverflowException.

**Comment by SWY1985** [comment]
Feedback by DracoNoir (possibly related):
- Odd crash with frigate several squares away from home city. Game crashed when map jumped back to it to begin its turn. Will investigate further.
- Linked to above, trireme was not lost after ending turn away from land but crashed game on move 2 of 3 when 1 square away from new continent; I _think_ frigate above was also 1 space away from new continent. Will investigate further.
- Game crashed after this: New game, settler moved 1 space to pick up a hut which had mercenaries inside. Next turn settler built city on same square (where hut was and mercenaries are) and game crashed after the 'meadow' screen, before showing city management. Will investigate further.
- Crash when screen jumped back to start settler turn after trireme moved. Will investigate further.
EDIT:: Ok, above 3 crashes appear to be the same and related to the screen jumping to or from a naval unit to begin the next unit's move. Crash can be replicated by moving a naval unit out of screen range of another unit (only so far tried with land units) and completing the turn. When the screen should jump to the next off-screen unit, the game will crash. Land to Land unit does not cause crash. EDIT: This is now not occurring. Only difference I can think of is that this is a custom world...?

**Comment by iStruggle** [comment]
I still cannot reproduce this anymore.  On custom or normal games.

**Comment by SWY1985** [comment]
This issue has been resolved.
