### ISSUE TITLE
Game can crash when founding city between two other cities

### ISSUE THREAD

**Issue by SWY1985** [SWY1985/CivOne#58]
Reported by deathfry on Civfanatics forums:

> I have bought 2 settlers, made the city in a distance of 1 square from previous city, and then, with the help of second settler, made the city between two cities. Game crashes.

![civ2](https://cloud.githubusercontent.com/assets/9248547/18377493/d5469c40-7667-11e6-8af9-c6de9537736d.jpg)

**Comment by iStruggle** [comment]
Crashes when city is built adjacent to another, including diagonals
