### ISSUE TITLE
Capital city cannot build a settler if the size of the city = 1...

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#62]
... no matter how many other cities you possess. It will just put it on hold until the city size reaches = 2. 

A neat way of preventing instant suicide at the beginning of the game. It appears Sid Meier thought of everything.

**EDIT: This actually relates to all the cities not just the capital. You basically cannot build a settler in any city with a size = 1. Hmm I thought this was possible in Civ1. Or am I confusing this with Civ2?**

**Comment by SWY1985** [comment]
I believe this 'protection' is only built in when playing as Chieftain. I will look into this.

**Comment by SWY1985** [comment]
I actually got a Settler without the city shrinking, both on Chieftain and Warlord level.
Needs more research.

**Comment by SWY1985** [comment]
Feedback by DracoNoir:
Famine in a city size 1 destroys city and and home units but produces a Settlers of NONE. (My) original game is more buggy than this - famined city is effectively destroyed after the famine notice, but doesn't actually disappear until clicked on or the map refreshes (move a non-central unit, visit another screen etc).

**Comment by iStruggle** [comment]
This is DracoNoir =]
Also meant to say that in the original, a settler does NOT appear when the city is starved.

**Comment by SWY1985** [comment]
I have dropped the Settlers unit for now. The game ends with the game over screen.

**Comment by AlexFolland** [comment]
It is important for certain strategies to be able to build a Settlers unit with only 1 population in the city.  I abuse this mechanic in Civilization for my tight city grid high tax strategy which allows building a Settlers unit every other turn.

**Comment by SWY1985** [comment]
Okay, here's the behaviour that I have tested in Civilization 474.01, which I consider to be the reference for CivOne.

When playing at Chieftain level, the following happens:
If you only have one city, even when you have sold the Palace, and your city size is 1, the Settler unit simply will not get built and the production box will overflow like this:
![image](https://cloud.githubusercontent.com/assets/9248547/24234535/2eb152aa-0f99-11e7-8493-30eead145cca.png)

![image](https://cloud.githubusercontent.com/assets/9248547/24234539/32fca26a-0f99-11e7-9598-63fd192b608b.png)

When playing on Warlock or higher, the Settlers unit will get built without the city getting destroyed in a city of size 1 (the current behaviour of CivOne).

Which is, I believe, a bug, but I'm going to implement it the same way and create a patch to fix this behaviour at a later point.

**Comment by SWY1985** [comment]
Okay, a bit more testing: In Civilization 474.01, it is simply impossible to 'delete' you city by building a Settlers unit in any city of size 1 on Chieftain level.
On other levels, when the City count is 1, building a Settlers unit will create the unit without shrinking the city size. The presence of a Palace does not affect this behaviour. The food stores will not be emptied by creating a Settlers unit in a city of size 1.

**Comment by AlexFolland** [comment]
Nice research!  I'm glad I can use this mechanic in CivOne.  :)  I often buy Settlers in size-1 cities after passing a turn and getting at least 1 production to halve the cost.
