### ISSUE TITLE
When changing the production to a lesser shield count change the status to "1 turn"

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#64]
In the production menu, all the units that have lesser requirements that the current shield count should have "1 turn".

CivONE:
![turns](https://cloud.githubusercontent.com/assets/21365802/18409583/9b37699c-774a-11e6-956e-943b7a191419.png)

Original CIV:
![original](https://cloud.githubusercontent.com/assets/21365802/18409589/d9190478-774a-11e6-948f-580e31bbbb0f.png)

**Comment by SWY1985** [comment]
This has been fixed in a recent commit:
https://github.com/SWY1985/CivOne/commit/f65941c0f7a808b96afad013410f286c43b57082
