### ISSUE TITLE
When moving units with a railroad through a city, the movement count should be reduced 

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#65]
If the city has railroad placed in its vicinity, the units moving with a railroad through a city should have their movement reduced by 1/3. Cities always act as having a normal road tile, even with the invention of railroad.

Frankly this is one of the most annoying bugs in Civ1 and you should probably just ignore this issue. They fixed this in Civ2.

**Comment by SWY1985** [comment]
I will implement this anyway, sorry. ;-)

**Comment by iStruggle** [comment]
is this still true if the city is built on a square which already contains RR?

**Comment by kazgaroth011** [comment]
iStruggle - yes it's still true
