### ISSUE TITLE
Change production in the city square by considering irrigation and roads

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#66]
In the tile where you build a city, consider that the city has an irrigation and road automatically built on this tile.

This means that if you build a city on plains it should have 2 food, 1 trade & 1 production (instead of 1 food, 0 trade, 1 production).

And if you build city on grassland it should have 2 food, 1 trade (instead of 2 food, 0 trade).

Naturally this also depends on the type of government.

**Comment by SWY1985** [comment]
Yeah, I wasn't sure about this. I will implement this.
