### ISSUE TITLE
Change city border line when units move in/from the city square

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#67]
A thick black line indicates that a unit is present in a city. 

Currently in CivONE when a unit moves a away from the city: first the line disappears and only then does a unit make a movement. It should be so that first the unit moves and then the line disappears.

Similarly in CivONE when a unit moves into an empty city: first the line appears and then a unit makes a movement. Again it should be the other way around.

This is nitpicking but it's just something I noticed.

**Comment by SWY1985** [comment]
That is incorrect behaviour and I will fix it soon. Thank you.
