### ISSUE TITLE
Correctly implement resources under all governments

### ISSUE THREAD

**Issue by SWY1985** [SWY1985/CivOne#74]
Feedback by DracoNoir:
= Resource errors (found so far and compared to terrain chart on civfanatics here: http://www.civfanatics.com/civ1/refc...v1terchart.htm ):
- Goverment appears to be monarchy at all times - ie no resource penalty for despotism at start of game(testing?)
- Grasslands 1 (without the nubbin =]) incorrectly displays and gives 1 shield instead of 0.
- Grasslands 2 (nubbin included!) correctly displays resources but gives 2 shields instead of 1.
- River 2 (assuming same staircase-looking terrain pattern implemented from original as River 1 and River 2 look the same =]) displays correct resources but gives 2 shields instead of 1. 
- Cities always seem to produce a minimum of 1 shield even if city is on a square giving no shields.
- Ocean incorrectly displays only 1 food. Should also have 2 trade. Incorrectly gives 1 shield and no trade. Food ok.
- Irrigated Grass 2 displays correctly but give 3 shields instead of 1.
- Irrigated grass 1 incorrectly displays (assuming i'm right about the starting govt. and based on grass2 giving 3 food) 2 food and 1 shield. Should be 3 food with no shield. Also incorrectly gives 2 shields.
- Forest displays correctly but gives only 1 shield instead of 2.
- Hills displays correctly but incorrectly gives 1 shield instead of 0.
- Irrigated Hills incorrectly displays 2 food instead of 3 and incorrectly gives 2 food instead of 3 and 2 shields instead of 0. EDIT: Actually the terrain chart on civfanatics is incorrect - original game gives 2 food for Irrigated Hills, but still no shields.
- Game(tundra) correctly displays 3 food, but gives 3 shields instead of 0.
- Mountains and Mined Mountains display correctly but gives 0 shields instead of 1 and 2 respectively.
- Oasis(desert)displays correctly, but gives 3 shields instead of 1.
- Irrigated Oasis displays correctly, but gives 4 shields instead of 1.
- Desert displays correctly but gives 0 shields instead of 1.
- Mined Desert displays correctly but gives 0 shields instead of 2.
- Irrigated Desert is fine.
- Horses (plains) displays correctly but gives 1 shield instead of 3.
- Irrigated Horses displays correctly but gives 2 shields instead of 3.
- Gold(mountain) displays correctly at 6 trade and 1 shield(confirming a fixed monarchy or communist govt.) but gives no shield.
- Oil(swamp) displays correctly but gives 1 shield instead of 4.
- Game(forest) displays correctly but gives 3 shields instead of 2.
- Coal(hills) displays correctly but gives 1 shield instead of 2.

**Comment by SWY1985** [comment]
I hope I've got everything correct now...

**Comment by kazgaroth011** [comment]
I've changed from Despotism to Monarchy, but I still get city production as in despotism:
![capture00009](https://cloud.githubusercontent.com/assets/21365802/18790190/2525f3d6-81ae-11e6-8fee-d995375812c0.png)

It worked fine yesterday and earlier today.

**Comment by SWY1985** [comment]
I believe that's linked to #130.
