### ISSUE TITLE
Still have interest?

### ISSUE THREAD

**Issue by chanakya35** [SWY1985/CivOne#8]
Hi @SWY1985 - Have you abandoned this or just on a sabbatical? It looks interesting and it piqued my interest because I like both Civ (for years now) as well as C#.

**Comment by chanakya35** [comment]
Got your message through civfanatics. I've already forked but yes do count me in as a contributor! It'll take me some time to digest the code and we ought to maybe discuss the multi-platform (mono) .NET aspect some time since I'm pretty much coming from a Microsoft background.  Cheers!

**Comment by SWY1985** [comment]
Hi there,
As long as you don't touch the GtkWindow file or any of the vscode .json files, everything should work out fine. On Windows, you don't even need to install Mono.
When you push code, I'll test it out on Linux and MacOS X and make changes where necessary.
Thank you so much for offering to help. Give me about a week to sort out the repository. After that we'll make a plan on what each of us can work on.
Kind regards,
SWY

**Comment by chanakya35** [comment]
Sounds good. I'll stay tuned; in the meantime I'll spend some time discovering the existing code and if inspired to implement anything, I'll do it on my fork and avoid the aforementioned UI/config components. One question: where can I find the GtkSharp libs you specifically reference for the .NET Client 4 framework in the solution? I grabbed the latest 3.1.3 from NuGet but this required me to "upgrade" the solution to full NET 4.6.1 for some reason.

**Comment by chanakya35** [comment]
Never mind for now - I was trying to start developing in VS Community 2015, but decided to install VS Code instead so I'll give this a shot. Nonetheless, let me know if you have any environment config advice including package management.

**Comment by SWY1985** [comment]
I've set up a wiki page on GitHub. The instructions are here: https://github.com/SWY1985/CivOne/wiki/How-to-build-and-run-CivOne%3F
Please let me know if anything is unclear or missing, I'll update the wiki page.

**Comment by SWY1985** [comment]
I'd recommend installing Mono, but if you don't want that, you can make the following changes to your tasks.json file:

`	"windows": {
		"command": "build.bat",
		**"args": ["msbuild"],**
		"tasks": [`

**Comment by SWY1985** [comment]
Hi, I didn't add this instruction to the wiki page yet: You should install the following extensions in Visual Studio Code: C# and Mono debugging.
The Mono debugging doesn't work in Windows, but you'll get a warning without it.
I ask you to, please, use Visual Studio Code when editing code. It will automatically enforce certain code styles to match the rest of the project. (ie. Tabs instead of spaces, UNIX line endings, utf-8 encoding...)
