### ISSUE TITLE
Trireme should be able to get lost at sea

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#85]
Trireme, Fighter, Bomber and Nuclear are kept after end of turn.

**Comment by iStruggle** [comment]
Also, sidebar should show split moves, eg 8 (16) on the first turn, both counting down, then 8 (8) on the second.

**Comment by kazgaroth011** [comment]
The trireme is not necessarily lost if it is out of the coast at the end of turn. It is an RNG event but I am not sure if it is 50-50 chance.

The bomber has 2 turns (one to make the bombing, one to get back home).

**Comment by SWY1985** [comment]
Air units already mentioned in #45, Trireme will be fixed
