### ISSUE TITLE
Able to build Nuclear units without Manhattan Project

### ISSUE THREAD

**Issue by iStruggle** [SWY1985/CivOne#86]

**Comment by SWY1985** [comment]
Wonders not yet implemented, so this is for testing purposes.
Will get fixed soon

**Comment by kazgaroth011** [comment]
Even though I haven't build Manhattan project, I was able to build a nuclear unit.

**Comment by SWY1985** [comment]
Oops... I think I removed my previous fix...

**Comment by SWY1985** [comment]
Nope, I actually made it so that building the Manhattan Project made Nuclear units obsolete. Fixed now... I blame Gandhi.
