### ISSUE TITLE
Unit cannot move in parallel to enemy units

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#90]
It can only move away from the enemy unit.

**Comment by SWY1985** [comment]
Need to research this...

**Comment by iStruggle** [comment]
This is correct behaviour? only diplomats and caravans can do this?

**Comment by SWY1985** [comment]
There's no code to take into account the enemy units yet... only code specifically forbidding interaction with the enemy (not occupy the same tile).
