### ISSUE TITLE
When discovering a hut, issue message before next unit

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#92]
The message upon discovering a hut should first be visible, and after pressing key or mouse button the message should disappear. Only then should the next waiting unit be visible.

Now CivONE switches to the next unit and immediately after then reveals the hut message.

**Comment by iStruggle** [comment]
This applies to all popups.  The game should in effect 'pause' behind any popup window.  The sidebar is blank.

**Comment by kazgaroth011** [comment]
I noticed this issue happening again. When I move to a hut the message pops up only after the screen centers on the next unit.

**Comment by SWY1985** [comment]
I may have broken this when I made a task out of the tribal hut dialog.

**Comment by SWY1985** [comment]
This issue has been resolved
