### ISSUE TITLE
When building a new city the shield count should be 0

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#93]
Tested this on a couple of cities and immediately after the city is build the shield count is not 0.

**Comment by SWY1985** [comment]
I can not reproduce this...

**Comment by iStruggle** [comment]
now testing also

**Comment by SWY1985** [comment]
Reminder: You can make screenshots by pressing Ctrl+F5 and you can upload screenshots to GitHub, if that helps. :-)

**Comment by kazgaroth011** [comment]
Just started a new game and well ... I cannot replicate this problem. But I am sure it happened yesterday when I was testing. Better leave this issue open and if it doesn't occur again you can delete it.

**Comment by SWY1985** [comment]
I have been able to reproduce it. The queue system fixes it.
Here's how I did it:
- Find a tribal hut with a skilled mercenary
- Make sure that the skilled mercenary has no moves left
- Found a new city
- The game auto skips a turn before jumping to the city manager, resources for the new turn have already been added
